"""
Guardrails
==========
Safety checks applied at the system's highest-risk boundaries:

- SQL generated by the LLM pipeline is executed directly against connected
  customer databases (see ``databridge_services/agents/query_formatter_agent.py``).
  ``is_safe_sql`` enforces that only a single, read-only SELECT/WITH statement
  ever reaches the database driver.
- Chat input flows straight into system prompts for several LLM calls.
  ``detect_prompt_injection`` flags common attempts to override those prompts.
- Uploaded files are trusted by extension alone elsewhere in the app.
  ``validate_upload_content`` cross-checks the file's magic bytes against the
  extension the client claims.
"""
import re
from typing import Optional, Tuple, List

# ============================================================
# SQL SAFETY
# ============================================================

# Keywords that have no place in a read-only reporting query. Matched
# anywhere in the statement (not just as the leading token) so that
# Postgres data-modifying CTEs, e.g. `WITH x AS (DELETE FROM t RETURNING *)
# SELECT * FROM x`, can't smuggle a write past a "starts with SELECT" check.
_DANGEROUS_SQL_KEYWORDS = [
    "INSERT", "UPDATE", "DELETE", "DROP", "ALTER", "TRUNCATE", "CREATE",
    "GRANT", "REVOKE", "ATTACH", "DETACH", "COPY", "EXEC", "EXECUTE",
    "MERGE", "CALL", "VACUUM", "REINDEX", "REPLACE", "RENAME", "LOCK",
    "UNLOCK", "PRAGMA", "INTO", "OUTFILE", "DUMPFILE", "XP_CMDSHELL",
    "SP_EXECUTESQL", "PG_READ_FILE", "PG_READ_BINARY_FILE", "PG_LS_DIR",
    "LOAD_FILE", "BENCHMARK",
]
_DANGEROUS_SQL_RE = re.compile(
    r"\b(" + "|".join(_DANGEROUS_SQL_KEYWORDS) + r")\b", re.IGNORECASE
)
_LEADING_STATEMENT_RE = re.compile(r"^\s*\(?\s*(SELECT|WITH)\b", re.IGNORECASE)
_LINE_COMMENT_RE = re.compile(r"--[^\n]*")
_BLOCK_COMMENT_RE = re.compile(r"/\*.*?\*/", re.DOTALL)


def _strip_sql_comments(sql: str) -> str:
    return _BLOCK_COMMENT_RE.sub(" ", _LINE_COMMENT_RE.sub(" ", sql))


def is_safe_sql(sql_query: Optional[str]) -> Tuple[bool, str]:
    """
    Only a single read-only SELECT/WITH...SELECT statement is considered
    safe. Everything else (DDL, DML, multi-statement, admin/file functions)
    is rejected before it can reach the database driver.

    Returns (is_safe, reason). reason is empty when is_safe is True.
    """
    if not sql_query or not sql_query.strip():
        return False, "Empty SQL query."

    cleaned = _strip_sql_comments(sql_query).strip()
    if not cleaned:
        return False, "Query contained no executable content after removing comments."

    # Reject stacked statements: allow at most one trailing semicolon.
    body = cleaned[:-1] if cleaned.endswith(";") else cleaned
    if ";" in body:
        return False, "Multiple/stacked SQL statements are not allowed."

    if not _LEADING_STATEMENT_RE.match(body):
        return False, "Only SELECT (or WITH ... SELECT) statements are allowed."

    match = _DANGEROUS_SQL_RE.search(body)
    if match:
        return False, f"Query contains a disallowed keyword: {match.group(1).upper()}."

    return True, ""


# ============================================================
# PROMPT INJECTION
# ============================================================

_PROMPT_INJECTION_PATTERNS = [
    r"ignore (all|any|the)?\s*(previous|prior|above)\s*instructions",
    r"disregard (all|any|the)?\s*(previous|prior|above)",
    r"forget (all|everything|your)\s*(previous|prior|instructions)?",
    r"you are now (a|an|no longer)",
    r"pretend (you are|to be) (an? )?(unrestricted|unfiltered|jailbroken|dan)",
    r"reveal (your|the)\s*(system prompt|system message|instructions)",
    r"print (your|the)\s*(system prompt|system message|instructions)",
    r"show me (your|the)\s*(system prompt|system message|instructions)",
    r"what (is|are) your (system prompt|instructions)",
    r"new instructions\s*:",
    r"override (your|the|previous)\s*instructions",
    r"do anything now",
    r"\bdan mode\b",
    r"\bjailbreak\b",
    r"developer mode",
    r"without (any )?restrictions",
    r"unfiltered (mode|response)",
    r"bypass (your|the|all)\s*(safety|restrictions|filters|rules)",
]
_PROMPT_INJECTION_RE = re.compile("|".join(_PROMPT_INJECTION_PATTERNS), re.IGNORECASE)


def detect_prompt_injection(text: Optional[str]) -> Tuple[bool, List[str]]:
    """
    Heuristic scan for common prompt-injection / jailbreak phrasing.
    Returns (flagged, matched_snippets). This is a best-effort filter, not a
    guarantee - it exists to catch obvious attempts without blocking normal
    conversation.
    """
    if not text:
        return False, []
    matches = sorted({m.group(0).lower() for m in _PROMPT_INJECTION_RE.finditer(text)})
    return (len(matches) > 0), matches


# ============================================================
# TEXT SANITIZATION
# ============================================================

_CONTROL_CHARS_RE = re.compile(r"[\x00-\x08\x0b\x0c\x0e-\x1f\x7f]")


def sanitize_text(text: Optional[str], max_length: int = 10000) -> str:
    """Strip null bytes/control characters and cap length."""
    if not text:
        return ""
    cleaned = _CONTROL_CHARS_RE.sub("", str(text)).strip()
    return cleaned[:max_length]


# ============================================================
# FILE UPLOAD CONTENT VALIDATION
# ============================================================

# Best-effort magic-byte signatures. Text-based/container formats that don't
# have a single reliable signature (txt, md, eml, msg, mbox) are intentionally
# left unchecked - extension allowlisting is the only guard for those.
_MAGIC_SIGNATURES = {
    "pdf": [b"%PDF"],
    "docx": [b"PK\x03\x04"],
    "jpg": [b"\xff\xd8\xff"],
    "png": [b"\x89PNG\r\n\x1a\n"],
    "gif": [b"GIF87a", b"GIF89a"],
    "mkv": [b"\x1a\x45\xdf\xa3"],
    "wav": [b"RIFF"],
    "avi": [b"RIFF"],
    "flac": [b"fLaC"],
}

MAX_UPLOAD_FILE_SIZE = 100 * 1024 * 1024  # 100MB, matches app-wide MAX_CONTENT_LENGTH


def validate_upload_content(header_bytes: bytes, extension: str) -> Tuple[bool, str]:
    """
    Cross-checks a file's leading bytes against the extension the client
    claims. Only extensions with a reliable signature are checked; anything
    else passes through (the caller's extension allowlist is the only guard
    for those formats).
    """
    ext = (extension or "").lower().lstrip(".")
    signatures = _MAGIC_SIGNATURES.get(ext)
    if not signatures:
        return True, ""
    if any(header_bytes.startswith(sig) for sig in signatures):
        return True, ""
    return False, f"File content does not match the claimed .{ext} format."
