#!/usr/bin/env python3
"""
db_lending.py
==============
Generates a realistic, synthetic NBFC / lending-company database
(loan origination -> disbursement -> EMI repayment schedule -> collections
-> payables -> NPA classification -> credit bureau -> ledger) with Indian
customer data, for use as a demo/test data source inside Saarthi.

This is a self-contained companion project (data + a stub validation API +
Excel reference tables + NBFC guideline docs live under lending_demo/) - it
does not touch the main Saarthi Flask app's models or logical databases; it
provisions its own Postgres database and can be registered as one more
"database connection" data source inside Saarthi once loaded.

ALL DATA IS SYNTHETIC. Names are generated by Faker's en_IN locale; PAN,
Aadhaar, account numbers, phone numbers etc. are randomly generated in the
right *format* and are not real identifiers.

Usage
-----
    python db_lending.py --scale small   # ~15 MB,  quick smoke test
    python db_lending.py --scale medium  # ~250 MB
    python db_lending.py --scale full    # ~1.5 GB  (default)

    python db_lending.py --scale full --db-url postgresql://user:pass@host:5432/postgres

Environment variables (used when --db-url is not given):
    LENDING_DATABASE_URL   base Postgres URL (server + credentials only;
                            the database name itself is always
                            "lending_demo_db", created if missing)
                            default: postgresql://saarthi:password@localhost:5432/postgres
"""

from __future__ import annotations

import argparse
import io
import os
import random
import time
from dataclasses import dataclass
from datetime import date, datetime, timedelta
from urllib.parse import urlparse

import numpy as np
import psycopg2
import psycopg2.extras
from faker import Faker
from psycopg2.extensions import ISOLATION_LEVEL_AUTOCOMMIT

# --------------------------------------------------------------------------
# Scale presets: row counts for the "base" master tables. Transaction-level
# tables (repayment_schedule, collections, transactions_ledger, ...) are
# derived from these, not set independently, so the whole dataset scales
# together and stays internally consistent.
# --------------------------------------------------------------------------
SCALE_PRESETS = {
    "tiny": dict(branches=5, employees_per_branch=4, agents=20, customers=500, apps_per_customer=1.2),
    "small": dict(branches=15, employees_per_branch=6, agents=80, customers=8_000, apps_per_customer=1.3),
    "medium": dict(branches=60, employees_per_branch=8, agents=500, customers=80_000, apps_per_customer=1.4),
    # Calibrated (see README) to land the loaded database around ~1.3-1.7 GB.
    "full": dict(branches=110, employees_per_branch=9, agents=1_600, customers=95_000, apps_per_customer=1.4),
}

COPY_BATCH_ROWS = 50_000
RNG_SEED = 20260822  # fixed seed -> reproducible dataset across runs

fake = Faker("en_IN")
Faker.seed(RNG_SEED)
random.seed(RNG_SEED)
np.random.seed(RNG_SEED)


# --------------------------------------------------------------------------
# Reference / lookup data
# --------------------------------------------------------------------------

# (city, state, a real-format pincode) - a representative spread of Indian
# metros, tier-2 and tier-3 towns, used for branch locations and, by
# extension, customer addresses.
INDIAN_CITIES = [
    ("Mumbai", "Maharashtra", "400001"), ("Pune", "Maharashtra", "411001"),
    ("Nagpur", "Maharashtra", "440001"), ("Nashik", "Maharashtra", "422001"),
    ("Thane", "Maharashtra", "400601"), ("Delhi", "Delhi", "110001"),
    ("New Delhi", "Delhi", "110002"), ("Bengaluru", "Karnataka", "560001"),
    ("Mysuru", "Karnataka", "570001"), ("Hubballi", "Karnataka", "580020"),
    ("Chennai", "Tamil Nadu", "600001"), ("Coimbatore", "Tamil Nadu", "641001"),
    ("Madurai", "Tamil Nadu", "625001"), ("Trichy", "Tamil Nadu", "620001"),
    ("Hyderabad", "Telangana", "500001"), ("Warangal", "Telangana", "506002"),
    ("Ahmedabad", "Gujarat", "380001"), ("Surat", "Gujarat", "395001"),
    ("Vadodara", "Gujarat", "390001"), ("Rajkot", "Gujarat", "360001"),
    ("Kolkata", "West Bengal", "700001"), ("Siliguri", "West Bengal", "734001"),
    ("Durgapur", "West Bengal", "713201"), ("Jaipur", "Rajasthan", "302001"),
    ("Jodhpur", "Rajasthan", "342001"), ("Udaipur", "Rajasthan", "313001"),
    ("Kota", "Rajasthan", "324001"), ("Lucknow", "Uttar Pradesh", "226001"),
    ("Kanpur", "Uttar Pradesh", "208001"), ("Varanasi", "Uttar Pradesh", "221001"),
    ("Agra", "Uttar Pradesh", "282001"), ("Noida", "Uttar Pradesh", "201301"),
    ("Ghaziabad", "Uttar Pradesh", "201001"), ("Prayagraj", "Uttar Pradesh", "211001"),
    ("Patna", "Bihar", "800001"), ("Gaya", "Bihar", "823001"),
    ("Bhopal", "Madhya Pradesh", "462001"), ("Indore", "Madhya Pradesh", "452001"),
    ("Jabalpur", "Madhya Pradesh", "482001"), ("Gwalior", "Madhya Pradesh", "474001"),
    ("Chandigarh", "Chandigarh", "160001"), ("Ludhiana", "Punjab", "141001"),
    ("Amritsar", "Punjab", "143001"), ("Jalandhar", "Punjab", "144001"),
    ("Bhubaneswar", "Odisha", "751001"), ("Cuttack", "Odisha", "753001"),
    ("Guwahati", "Assam", "781001"), ("Ranchi", "Jharkhand", "834001"),
    ("Jamshedpur", "Jharkhand", "831001"), ("Raipur", "Chhattisgarh", "492001"),
    ("Thiruvananthapuram", "Kerala", "695001"), ("Kochi", "Kerala", "682001"),
    ("Kozhikode", "Kerala", "673001"), ("Visakhapatnam", "Andhra Pradesh", "530001"),
    ("Vijayawada", "Andhra Pradesh", "520001"), ("Guntur", "Andhra Pradesh", "522001"),
    ("Dehradun", "Uttarakhand", "248001"), ("Shimla", "Himachal Pradesh", "171001"),
    ("Panaji", "Goa", "403001"), ("Gurugram", "Haryana", "122001"),
    ("Faridabad", "Haryana", "121001"), ("Nagercoil", "Tamil Nadu", "629001"),
    ("Salem", "Tamil Nadu", "636001"), ("Aurangabad", "Maharashtra", "431001"),
    ("Solapur", "Maharashtra", "413001"), ("Meerut", "Uttar Pradesh", "250001"),
    ("Bareilly", "Uttar Pradesh", "243001"), ("Moradabad", "Uttar Pradesh", "244001"),
]

OCCUPATIONS = [
    ("Salaried - Private Sector", 0.40), ("Salaried - Government", 0.12),
    ("Self Employed - Business", 0.22), ("Self Employed - Professional", 0.08),
    ("Agriculturist", 0.08), ("Retired", 0.05), ("Homemaker", 0.05),
]

EMPLOYEE_ROLES = [
    ("Branch Manager", 1), ("Credit Analyst", 3), ("Relationship Manager", 4),
    ("Collections Officer", 3), ("Operations Executive", 2), ("Teller", 2),
]

# Loan product catalogue modeled on a typical Indian NBFC's book (rates are
# illustrative market ranges circa 2024-2025, not any real lender's actual
# card rates).
LOAN_PRODUCTS = [
    # code, name, category, min_amt, max_amt, min_tenure_m, max_tenure_m, rate_min, rate_max, proc_fee_pct
    ("PL", "Personal Loan", "Personal", 50_000, 2_000_000, 12, 60, 13.5, 24.0, 2.00),
    ("GL", "Gold Loan", "Gold", 10_000, 2_500_000, 3, 24, 9.0, 14.5, 0.50),
    ("TW", "Two-Wheeler Loan", "Vehicle", 30_000, 250_000, 12, 48, 11.5, 18.0, 1.50),
    ("UCL", "Used Car Loan", "Vehicle", 100_000, 1_500_000, 12, 60, 12.0, 17.5, 1.25),
    ("NCL", "New Car Loan", "Vehicle", 200_000, 3_000_000, 12, 84, 9.5, 13.5, 1.00),
    ("MSME", "MSME Business Loan", "Business", 100_000, 10_000_000, 12, 84, 15.5, 22.0, 2.00),
    ("LAP", "Loan Against Property", "Secured", 500_000, 30_000_000, 24, 180, 9.5, 14.0, 1.00),
    ("CD", "Consumer Durable Loan", "Consumer", 5_000, 200_000, 3, 24, 18.0, 28.0, 2.50),
    ("MFI", "Microfinance (JLG) Loan", "Microfinance", 10_000, 100_000, 6, 24, 21.0, 26.0, 1.00),
    ("EDU", "Education Loan", "Education", 100_000, 4_000_000, 12, 120, 10.5, 15.0, 1.00),
    ("HL", "Home Loan", "Housing", 500_000, 50_000_000, 60, 300, 8.5, 11.5, 0.50),
    ("HLTU", "Home Loan Top-up", "Housing", 100_000, 5_000_000, 24, 180, 10.0, 13.0, 0.75),
]

PAYMENT_MODES = ["NACH", "UPI", "NEFT", "Cheque", "Cash", "Auto-Debit Card"]

GENDERS = ["Male", "Female"]

BANK_NAMES = [
    "HDFC Bank", "ICICI Bank", "State Bank of India", "Axis Bank", "Punjab National Bank",
    "Kotak Mahindra Bank", "Bank of Baroda", "IDFC FIRST Bank", "Yes Bank", "IndusInd Bank",
    "Canara Bank", "Union Bank of India", "Federal Bank",
]

INSURANCE_PARTNERS = ["HDFC Life", "ICICI Prudential", "SBI Life", "Tata AIG", "Bajaj Allianz", "Star Health"]


# --------------------------------------------------------------------------
# Small helpers
# --------------------------------------------------------------------------

def log(msg: str) -> None:
    print(f"[{datetime.now().strftime('%H:%M:%S')}] {msg}", flush=True)


def derive_db_url(base_url: str, db_name: str) -> str:
    parsed = urlparse(base_url)
    return parsed._replace(path=f"/{db_name}").geturl()


def gen_pan() -> str:
    letters1 = "".join(random.choices("ABCDEFGHIJKLMNOPQRSTUVWXYZ", k=5))
    digits = "".join(random.choices("0123456789", k=4))
    letter2 = random.choice("ABCDEFGHIJKLMNOPQRSTUVWXYZ")
    return f"{letters1}{digits}{letter2}"


def gen_aadhaar_masked() -> str:
    last4 = "".join(random.choices("0123456789", k=4))
    return f"XXXX-XXXX-{last4}"


def gen_mobile() -> str:
    first = random.choice("6789")
    rest = "".join(random.choices("0123456789", k=9))
    return f"+91{first}{rest}"


def gen_ifsc(bank_name: str) -> str:
    prefix = "".join(ch for ch in bank_name.upper() if ch.isalpha())[:4].ljust(4, "X")
    return f"{prefix}0{random.randint(100000, 999999):06d}"[:11]


def weighted_choice(pairs):
    values, weights = zip(*pairs)
    return random.choices(values, weights=weights, k=1)[0]


def emi_amount(principal: float, annual_rate: float, tenure_months: int) -> float:
    r = annual_rate / 12 / 100
    if r == 0:
        return round(principal / tenure_months, 2)
    factor = (1 + r) ** tenure_months
    return round(principal * r * factor / (factor - 1), 2)


def random_date(start: date, end: date) -> date:
    delta_days = (end - start).days
    if delta_days <= 0:
        return start
    return start + timedelta(days=random.randint(0, delta_days))


# --------------------------------------------------------------------------
# Schema
# --------------------------------------------------------------------------

SCHEMA_SQL = """
DROP TABLE IF EXISTS transactions_ledger CASCADE;
DROP TABLE IF EXISTS credit_bureau_records CASCADE;
DROP TABLE IF EXISTS npa_classification CASCADE;
DROP TABLE IF EXISTS payables CASCADE;
DROP TABLE IF EXISTS collections CASCADE;
DROP TABLE IF EXISTS repayment_schedule CASCADE;
DROP TABLE IF EXISTS loans CASCADE;
DROP TABLE IF EXISTS loan_applications CASCADE;
DROP TABLE IF EXISTS customers CASCADE;
DROP TABLE IF EXISTS loan_products CASCADE;
DROP TABLE IF EXISTS agents CASCADE;
DROP TABLE IF EXISTS employees CASCADE;
DROP TABLE IF EXISTS branches CASCADE;

CREATE TABLE branches (
    branch_id       INTEGER PRIMARY KEY,
    branch_code     VARCHAR(10) UNIQUE NOT NULL,
    branch_name     VARCHAR(120) NOT NULL,
    city            VARCHAR(80) NOT NULL,
    state           VARCHAR(80) NOT NULL,
    pincode         VARCHAR(6) NOT NULL,
    region          VARCHAR(20) NOT NULL,
    opened_date     DATE NOT NULL,
    is_active       BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE TABLE employees (
    employee_id     INTEGER PRIMARY KEY,
    employee_code   VARCHAR(15) UNIQUE NOT NULL,
    branch_id       INTEGER NOT NULL REFERENCES branches(branch_id),
    full_name       VARCHAR(120) NOT NULL,
    designation     VARCHAR(40) NOT NULL,
    email           VARCHAR(120),
    mobile          VARCHAR(15),
    date_joined     DATE NOT NULL,
    is_active       BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE TABLE agents (
    agent_id        INTEGER PRIMARY KEY,
    agent_code      VARCHAR(15) UNIQUE NOT NULL,
    agent_name      VARCHAR(120) NOT NULL,
    agency_name     VARCHAR(150),
    branch_id       INTEGER NOT NULL REFERENCES branches(branch_id),
    mobile          VARCHAR(15),
    commission_rate NUMERIC(5,2) NOT NULL,
    empanelled_date DATE NOT NULL,
    is_active       BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE TABLE loan_products (
    product_id          SMALLINT PRIMARY KEY,
    product_code        VARCHAR(10) UNIQUE NOT NULL,
    product_name        VARCHAR(80) NOT NULL,
    category            VARCHAR(30) NOT NULL,
    min_amount          NUMERIC(14,2) NOT NULL,
    max_amount          NUMERIC(14,2) NOT NULL,
    min_tenure_months   SMALLINT NOT NULL,
    max_tenure_months   SMALLINT NOT NULL,
    interest_rate_min   NUMERIC(5,2) NOT NULL,
    interest_rate_max   NUMERIC(5,2) NOT NULL,
    processing_fee_pct  NUMERIC(5,2) NOT NULL
);

CREATE TABLE customers (
    customer_id     INTEGER PRIMARY KEY,
    customer_code   VARCHAR(15) UNIQUE NOT NULL,
    first_name      VARCHAR(60) NOT NULL,
    last_name       VARCHAR(60) NOT NULL,
    gender          VARCHAR(10) NOT NULL,
    date_of_birth   DATE NOT NULL,
    pan_number      VARCHAR(10) UNIQUE NOT NULL,
    aadhaar_masked  VARCHAR(15) NOT NULL,
    mobile          VARCHAR(15) NOT NULL,
    email           VARCHAR(120),
    address_line    VARCHAR(160),
    city            VARCHAR(80) NOT NULL,
    state           VARCHAR(80) NOT NULL,
    pincode         VARCHAR(6) NOT NULL,
    occupation      VARCHAR(40) NOT NULL,
    monthly_income  NUMERIC(12,2) NOT NULL,
    cibil_score     SMALLINT,
    kyc_status      VARCHAR(20) NOT NULL,
    home_branch_id  INTEGER NOT NULL REFERENCES branches(branch_id),
    onboarded_date  DATE NOT NULL
);

CREATE TABLE loan_applications (
    application_id      BIGINT PRIMARY KEY,
    application_number  VARCHAR(20) UNIQUE NOT NULL,
    customer_id         INTEGER NOT NULL REFERENCES customers(customer_id),
    product_id          SMALLINT NOT NULL REFERENCES loan_products(product_id),
    branch_id           INTEGER NOT NULL REFERENCES branches(branch_id),
    agent_id            INTEGER REFERENCES agents(agent_id),
    credit_analyst_id   INTEGER REFERENCES employees(employee_id),
    applied_date        DATE NOT NULL,
    requested_amount    NUMERIC(14,2) NOT NULL,
    requested_tenure_months SMALLINT NOT NULL,
    status              VARCHAR(20) NOT NULL,
    rejection_reason    VARCHAR(120),
    decision_date       DATE
);

CREATE TABLE loans (
    loan_id             BIGINT PRIMARY KEY,
    loan_account_number VARCHAR(20) UNIQUE NOT NULL,
    application_id      BIGINT UNIQUE NOT NULL REFERENCES loan_applications(application_id),
    customer_id         INTEGER NOT NULL REFERENCES customers(customer_id),
    product_id          SMALLINT NOT NULL REFERENCES loan_products(product_id),
    branch_id           INTEGER NOT NULL REFERENCES branches(branch_id),
    sanctioned_amount   NUMERIC(14,2) NOT NULL,
    disbursed_amount    NUMERIC(14,2) NOT NULL,
    interest_rate       NUMERIC(5,2) NOT NULL,
    tenure_months       SMALLINT NOT NULL,
    emi_amount          NUMERIC(14,2) NOT NULL,
    disbursement_date   DATE NOT NULL,
    first_emi_date      DATE NOT NULL,
    maturity_date       DATE NOT NULL,
    disbursing_bank     VARCHAR(60),
    loan_status         VARCHAR(20) NOT NULL,
    closure_date        DATE,
    risk_profile        VARCHAR(10) NOT NULL,
    current_dpd         INTEGER NOT NULL DEFAULT 0,
    npa_flag            BOOLEAN NOT NULL DEFAULT FALSE
);

CREATE TABLE repayment_schedule (
    schedule_id         BIGINT PRIMARY KEY,
    loan_id             BIGINT NOT NULL REFERENCES loans(loan_id),
    installment_number  SMALLINT NOT NULL,
    due_date            DATE NOT NULL,
    opening_principal   NUMERIC(14,2) NOT NULL,
    principal_due       NUMERIC(14,2) NOT NULL,
    interest_due        NUMERIC(14,2) NOT NULL,
    emi_due             NUMERIC(14,2) NOT NULL,
    closing_principal   NUMERIC(14,2) NOT NULL,
    amount_paid         NUMERIC(14,2) NOT NULL DEFAULT 0,
    paid_date           DATE,
    payment_status      VARCHAR(20) NOT NULL,
    dpd_days            INTEGER NOT NULL DEFAULT 0
);

CREATE TABLE collections (
    collection_id       BIGINT PRIMARY KEY,
    receipt_number      VARCHAR(20) UNIQUE NOT NULL,
    loan_id             BIGINT NOT NULL REFERENCES loans(loan_id),
    schedule_id         BIGINT REFERENCES repayment_schedule(schedule_id),
    customer_id         INTEGER NOT NULL REFERENCES customers(customer_id),
    collection_date     DATE NOT NULL,
    principal_component NUMERIC(14,2) NOT NULL,
    interest_component  NUMERIC(14,2) NOT NULL,
    penalty_component   NUMERIC(14,2) NOT NULL DEFAULT 0,
    total_amount        NUMERIC(14,2) NOT NULL,
    payment_mode        VARCHAR(20) NOT NULL,
    collected_by_employee_id INTEGER REFERENCES employees(employee_id),
    collected_by_agent_id    INTEGER REFERENCES agents(agent_id)
);

CREATE TABLE payables (
    payable_id          BIGINT PRIMARY KEY,
    payable_type        VARCHAR(30) NOT NULL,
    payee_name          VARCHAR(150) NOT NULL,
    branch_id           INTEGER REFERENCES branches(branch_id),
    agent_id            INTEGER REFERENCES agents(agent_id),
    related_loan_id     BIGINT REFERENCES loans(loan_id),
    invoice_number      VARCHAR(25) UNIQUE NOT NULL,
    amount              NUMERIC(14,2) NOT NULL,
    due_date            DATE NOT NULL,
    paid_date           DATE,
    status              VARCHAR(15) NOT NULL
);

CREATE TABLE npa_classification (
    npa_id              BIGINT PRIMARY KEY,
    loan_id             BIGINT NOT NULL REFERENCES loans(loan_id),
    as_of_date          DATE NOT NULL,
    dpd_bucket          VARCHAR(15) NOT NULL,
    asset_classification VARCHAR(15) NOT NULL,
    outstanding_principal NUMERIC(14,2) NOT NULL,
    provisioning_pct    NUMERIC(5,2) NOT NULL,
    provisioning_amount NUMERIC(14,2) NOT NULL
);

CREATE TABLE credit_bureau_records (
    record_id           BIGINT PRIMARY KEY,
    customer_id         INTEGER NOT NULL REFERENCES customers(customer_id),
    bureau_name         VARCHAR(20) NOT NULL,
    score               SMALLINT NOT NULL,
    report_date         DATE NOT NULL,
    existing_loans_count SMALLINT NOT NULL,
    total_outstanding   NUMERIC(14,2) NOT NULL,
    enquiries_last_6m   SMALLINT NOT NULL
);

CREATE TABLE transactions_ledger (
    transaction_id      BIGINT PRIMARY KEY,
    reference_number    VARCHAR(25) UNIQUE NOT NULL,
    loan_id             BIGINT REFERENCES loans(loan_id),
    customer_id         INTEGER REFERENCES customers(customer_id),
    transaction_type    VARCHAR(20) NOT NULL,
    transaction_date    DATE NOT NULL,
    amount              NUMERIC(14,2) NOT NULL,
    payment_mode        VARCHAR(30) NOT NULL,
    status              VARCHAR(15) NOT NULL
);
"""

INDEX_SQL = """
CREATE INDEX idx_employees_branch ON employees(branch_id);
CREATE INDEX idx_agents_branch ON agents(branch_id);
CREATE INDEX idx_customers_branch ON customers(home_branch_id);
CREATE INDEX idx_customers_pan ON customers(pan_number);
CREATE INDEX idx_apps_customer ON loan_applications(customer_id);
CREATE INDEX idx_apps_product ON loan_applications(product_id);
CREATE INDEX idx_apps_status ON loan_applications(status);
CREATE INDEX idx_loans_customer ON loans(customer_id);
CREATE INDEX idx_loans_product ON loans(product_id);
CREATE INDEX idx_loans_status ON loans(loan_status);
CREATE INDEX idx_loans_npa ON loans(npa_flag);
CREATE INDEX idx_schedule_loan ON repayment_schedule(loan_id);
CREATE INDEX idx_schedule_due_date ON repayment_schedule(due_date);
CREATE INDEX idx_schedule_status ON repayment_schedule(payment_status);
CREATE INDEX idx_collections_loan ON collections(loan_id);
CREATE INDEX idx_collections_customer ON collections(customer_id);
CREATE INDEX idx_collections_date ON collections(collection_date);
CREATE INDEX idx_payables_status ON payables(status);
CREATE INDEX idx_payables_agent ON payables(agent_id);
CREATE INDEX idx_npa_loan ON npa_classification(loan_id);
CREATE INDEX idx_bureau_customer ON credit_bureau_records(customer_id);
CREATE INDEX idx_ledger_loan ON transactions_ledger(loan_id);
CREATE INDEX idx_ledger_date ON transactions_ledger(transaction_date);
CREATE INDEX idx_ledger_type ON transactions_ledger(transaction_type);
"""


def ensure_database(base_url: str, db_name: str) -> None:
    parsed = urlparse(base_url)
    maint_conn = psycopg2.connect(
        dbname="postgres", user=parsed.username, password=parsed.password,
        host=parsed.hostname, port=parsed.port or 5432,
    )
    maint_conn.set_isolation_level(ISOLATION_LEVEL_AUTOCOMMIT)
    try:
        with maint_conn.cursor() as cur:
            cur.execute("SELECT 1 FROM pg_database WHERE datname = %s", (db_name,))
            if not cur.fetchone():
                log(f"Creating database '{db_name}'...")
                cur.execute(f'CREATE DATABASE "{db_name}"')
            else:
                log(f"Database '{db_name}' already exists - will be reset (schema DROP/CREATE).")
    finally:
        maint_conn.close()


class CopyWriter:
    """Buffers rows for one table and flushes them via COPY in batches."""

    def __init__(self, conn, table: str, columns: list[str], depends_on: list["CopyWriter"] | None = None):
        self.conn = conn
        self.table = table
        self.columns = columns
        self.buffer = io.StringIO()
        self.count_in_buffer = 0
        self.total = 0
        # Writers for tables this one holds foreign keys into. Flushed
        # before this writer's own buffer so a row can never reference an
        # id that hasn't actually been COPY'd (and committed) yet - the two
        # writers otherwise fill and auto-flush independently of each other.
        self.depends_on = depends_on or []

    @staticmethod
    def _fmt(value) -> str:
        if value is None:
            return r"\N"
        if isinstance(value, bool):
            return "t" if value else "f"
        if isinstance(value, (date, datetime)):
            return value.isoformat()
        if isinstance(value, str):
            return value.replace("\\", "\\\\").replace("\t", "\\t").replace("\n", "\\n").replace("\r", "")
        return str(value)

    def add(self, row: tuple) -> None:
        self.buffer.write("\t".join(self._fmt(v) for v in row))
        self.buffer.write("\n")
        self.count_in_buffer += 1
        if self.count_in_buffer >= COPY_BATCH_ROWS:
            self.flush()

    def flush(self) -> None:
        for dep in self.depends_on:
            dep.flush()
        if self.count_in_buffer == 0:
            return
        self.buffer.seek(0)
        with self.conn.cursor() as cur:
            cur.copy_expert(
                f"COPY {self.table} ({', '.join(self.columns)}) FROM STDIN WITH (FORMAT text)",
                self.buffer,
            )
        self.conn.commit()
        self.total += self.count_in_buffer
        self.buffer = io.StringIO()
        self.count_in_buffer = 0


# --------------------------------------------------------------------------
# Generators
# --------------------------------------------------------------------------

@dataclass
class Branch:
    branch_id: int
    city: str
    state: str
    pincode: str
    region: str


REGION_BY_STATE = {
    "Maharashtra": "West", "Gujarat": "West", "Goa": "West", "Rajasthan": "West",
    "Delhi": "North", "Punjab": "North", "Haryana": "North", "Uttar Pradesh": "North",
    "Uttarakhand": "North", "Himachal Pradesh": "North", "Chandigarh": "North",
    "Karnataka": "South", "Tamil Nadu": "South", "Kerala": "South", "Telangana": "South",
    "Andhra Pradesh": "South",
    "West Bengal": "East", "Odisha": "East", "Bihar": "East", "Jharkhand": "East",
    "Assam": "East",
    "Madhya Pradesh": "Central", "Chhattisgarh": "Central",
}


def generate_branches(n: int, conn) -> list[Branch]:
    writer = CopyWriter(conn, "branches", [
        "branch_id", "branch_code", "branch_name", "city", "state", "pincode",
        "region", "opened_date", "is_active",
    ])
    branches = []
    cities_cycle = (INDIAN_CITIES * (n // len(INDIAN_CITIES) + 1))[:n]
    random.shuffle(cities_cycle)
    for i, (city, state, pincode) in enumerate(cities_cycle, start=1):
        region = REGION_BY_STATE.get(state, "Central")
        opened = random_date(date(2008, 1, 1), date(2024, 6, 30))
        code = f"BR{i:04d}"
        name = f"{city} - {region} Branch" if cities_cycle.count((city, state, pincode)) == 1 else f"{city} Branch {i}"
        writer.add((i, code, name, city, state, pincode, region, opened, True))
        branches.append(Branch(i, city, state, pincode, region))
    writer.flush()
    log(f"branches: {writer.total} rows")
    return branches


def generate_employees(n_per_branch: int, branches: list[Branch], conn) -> list[int]:
    writer = CopyWriter(conn, "employees", [
        "employee_id", "employee_code", "branch_id", "full_name", "designation",
        "email", "mobile", "date_joined", "is_active",
    ])
    employee_ids_by_branch: dict[int, list[int]] = {b.branch_id: [] for b in branches}
    eid = 0
    for b in branches:
        roles = []
        for role, count in EMPLOYEE_ROLES:
            roles += [role] * count
        random.shuffle(roles)
        for role in roles[:n_per_branch] if n_per_branch < len(roles) else roles:
            eid += 1
            name = fake.name()
            joined = random_date(date(2010, 1, 1), date(2025, 12, 31))
            email = f"{name.lower().replace(' ', '.')}{eid}@lendwellnbfc.in"
            writer.add((eid, f"EMP{eid:06d}", b.branch_id, name, role, email, gen_mobile(), joined, True))
            employee_ids_by_branch[b.branch_id].append(eid)
    writer.flush()
    log(f"employees: {writer.total} rows")
    return employee_ids_by_branch


def generate_agents(n: int, branches: list[Branch], conn) -> list[int]:
    writer = CopyWriter(conn, "agents", [
        "agent_id", "agent_code", "agent_name", "agency_name", "branch_id",
        "mobile", "commission_rate", "empanelled_date", "is_active",
    ])
    agent_ids_by_branch: dict[int, list[int]] = {b.branch_id: [] for b in branches}
    for i in range(1, n + 1):
        b = random.choice(branches)
        name = fake.name()
        agency = f"{name.split()[-1]} Financial Services" if random.random() < 0.6 else None
        empanelled = random_date(date(2012, 1, 1), date(2025, 12, 31))
        writer.add((i, f"AGT{i:06d}", name, agency, b.branch_id, gen_mobile(),
                    round(random.uniform(0.5, 3.0), 2), empanelled, random.random() > 0.05))
        agent_ids_by_branch[b.branch_id].append(i)
    writer.flush()
    log(f"agents: {writer.total} rows")
    return agent_ids_by_branch


def generate_loan_products(conn) -> list[dict]:
    writer = CopyWriter(conn, "loan_products", [
        "product_id", "product_code", "product_name", "category", "min_amount",
        "max_amount", "min_tenure_months", "max_tenure_months",
        "interest_rate_min", "interest_rate_max", "processing_fee_pct",
    ])
    products = []
    for i, p in enumerate(LOAN_PRODUCTS, start=1):
        code, name, category, min_amt, max_amt, min_t, max_t, r_min, r_max, fee = p
        writer.add((i, code, name, category, min_amt, max_amt, min_t, max_t, r_min, r_max, fee))
        products.append(dict(product_id=i, code=code, name=name, category=category,
                              min_amount=min_amt, max_amount=max_amt,
                              min_tenure=min_t, max_tenure=max_t,
                              rate_min=r_min, rate_max=r_max, fee=fee))
    writer.flush()
    log(f"loan_products: {writer.total} rows")
    return products


@dataclass
class Customer:
    customer_id: int
    branch_id: int
    city: str
    state: str
    pincode: str
    income: float
    cibil: int
    dob: date


def generate_customers(n: int, branches: list[Branch], conn) -> list[Customer]:
    writer = CopyWriter(conn, "customers", [
        "customer_id", "customer_code", "first_name", "last_name", "gender",
        "date_of_birth", "pan_number", "aadhaar_masked", "mobile", "email",
        "address_line", "city", "state", "pincode", "occupation",
        "monthly_income", "cibil_score", "kyc_status", "home_branch_id", "onboarded_date",
    ])
    customers = []
    used_pans: set[str] = set()
    for i in range(1, n + 1):
        gender = random.choice(GENDERS)
        first = fake.first_name_male() if gender == "Male" else fake.first_name_female()
        last = fake.last_name()
        dob = fake.date_of_birth(minimum_age=21, maximum_age=68)
        pan = gen_pan()
        while pan in used_pans:
            pan = gen_pan()
        used_pans.add(pan)
        b = random.choice(branches)
        occupation = weighted_choice(OCCUPATIONS)
        if occupation == "Salaried - Government":
            income = max(18_000, np.random.lognormal(mean=10.6, sigma=0.35))
        elif occupation == "Self Employed - Business":
            income = max(15_000, np.random.lognormal(mean=10.7, sigma=0.6))
        elif occupation == "Agriculturist":
            income = max(10_000, np.random.lognormal(mean=10.1, sigma=0.5))
        else:
            income = max(12_000, np.random.lognormal(mean=10.5, sigma=0.5))
        cibil = int(np.clip(np.random.normal(715, 90), 300, 900))
        onboarded = random_date(date(2015, 1, 1), date(2026, 7, 1))
        email = f"{first.lower()}.{last.lower()}{i}@example.com" if random.random() > 0.15 else None
        writer.add((
            i, f"CUS{i:07d}", first, last, gender, dob, pan, gen_aadhaar_masked(),
            gen_mobile(), email, fake.street_address(), b.city, b.state, b.pincode,
            occupation, round(float(income), 2), cibil,
            weighted_choice([("Verified", 0.92), ("Pending", 0.05), ("Rejected", 0.03)]),
            b.branch_id, onboarded,
        ))
        customers.append(Customer(i, b.branch_id, b.city, b.state, b.pincode,
                                   float(income), cibil, dob))
    writer.flush()
    log(f"customers: {writer.total} rows")
    return customers


# Risk profile mix drives repayment behaviour downstream.
RISK_PROFILES = [("Good", 0.68), ("Average", 0.22), ("Risky", 0.10)]
APP_STATUS_WEIGHTS_BY_CIBIL_BAND = {
    # (approved, rejected, withdrawn) — better CIBIL -> higher approval odds
    "high": (0.90, 0.06, 0.04),
    "mid": (0.72, 0.20, 0.08),
    "low": (0.38, 0.52, 0.10),
}
REJECTION_REASONS = [
    "Low CIBIL score", "Income to obligation ratio too high", "Incomplete KYC documents",
    "Negative credit bureau remarks", "Unable to verify address", "Existing overdue loan",
    "Employer not in approved list", "Applicant below minimum vintage",
]


def cibil_band(score: int) -> str:
    if score >= 720:
        return "high"
    if score >= 650:
        return "mid"
    return "low"


@dataclass
class LoanApp:
    application_id: int
    customer: Customer
    product: dict
    branch_id: int
    status: str
    applied_date: date
    amount: float
    tenure: int


def generate_applications_and_loans(
    customers: list[Customer], products: list[dict],
    employee_ids_by_branch: dict, agent_ids_by_branch: dict,
    apps_per_customer: float, conn,
):
    app_writer = CopyWriter(conn, "loan_applications", [
        "application_id", "application_number", "customer_id", "product_id", "branch_id",
        "agent_id", "credit_analyst_id", "applied_date", "requested_amount",
        "requested_tenure_months", "status", "rejection_reason", "decision_date",
    ])
    loan_writer = CopyWriter(conn, "loans", [
        "loan_id", "loan_account_number", "application_id", "customer_id", "product_id",
        "branch_id", "sanctioned_amount", "disbursed_amount", "interest_rate", "tenure_months",
        "emi_amount", "disbursement_date", "first_emi_date", "maturity_date",
        "disbursing_bank", "loan_status", "closure_date", "risk_profile", "current_dpd", "npa_flag",
    ], depends_on=[app_writer])

    approved_loans: list[dict] = []
    app_id = 0
    loan_id = 0
    today = date(2026, 8, 22)

    for cust in customers:
        n_apps = np.random.poisson(apps_per_customer) or 1
        for _ in range(n_apps):
            app_id += 1
            product = random.choice(products)
            band = cibil_band(cust.cibil)
            approved_p, rejected_p, withdrawn_p = APP_STATUS_WEIGHTS_BY_CIBIL_BAND[band]

            lo, hi = product["min_amount"], min(product["max_amount"], cust.income * 30)
            hi = max(hi, lo * 1.05)
            amount = round(random.uniform(lo, hi), -3) or lo
            tenure = random.randint(product["min_tenure"], product["max_tenure"])
            applied = random_date(date(2019, 1, 1), today - timedelta(days=1))

            status = weighted_choice([
                ("Approved", approved_p), ("Rejected", rejected_p), ("Withdrawn", withdrawn_p),
            ])
            branch_id = cust.branch_id
            agent_pool = agent_ids_by_branch.get(branch_id) or []
            agent_id = random.choice(agent_pool) if agent_pool and random.random() < 0.55 else None
            analyst_pool = employee_ids_by_branch.get(branch_id) or []
            analyst_id = random.choice(analyst_pool) if analyst_pool else None
            decision_date = applied + timedelta(days=random.randint(1, 21))
            rejection_reason = random.choice(REJECTION_REASONS) if status == "Rejected" else None

            app_writer.add((
                app_id, f"APP{app_id:08d}", cust.customer_id, product["product_id"], branch_id,
                agent_id, analyst_id, applied, amount, tenure, status, rejection_reason,
                decision_date if status != "Submitted" else None,
            ))

            if status != "Approved":
                continue

            # A fraction of approvals never get disbursed (customer backed out).
            if random.random() < 0.04:
                continue

            loan_id += 1
            rate = round(random.uniform(product["rate_min"], product["rate_max"]), 2)
            disbursement_date = decision_date + timedelta(days=random.randint(1, 10))
            if disbursement_date >= today:
                continue
            first_emi = (disbursement_date.replace(day=1) + timedelta(days=32)).replace(day=min(disbursement_date.day, 28))
            emi = emi_amount(amount, rate, tenure)
            maturity = first_emi + timedelta(days=30 * tenure)
            risk_profile = weighted_choice(RISK_PROFILES)

            months_elapsed = max(0, (today.year - disbursement_date.year) * 12 + (today.month - disbursement_date.month))
            closed_naturally = months_elapsed >= tenure and random.random() < 0.97
            foreclosed = (not closed_naturally) and months_elapsed >= 6 and random.random() < 0.06
            loan_status = "Closed" if closed_naturally else ("Foreclosed" if foreclosed else "Active")
            closure_date = None
            if loan_status in ("Closed", "Foreclosed"):
                closure_date = min(maturity, disbursement_date + timedelta(days=30 * min(tenure, months_elapsed)))

            loan = dict(
                loan_id=loan_id, application_id=app_id, customer=cust, product=product,
                branch_id=branch_id, sanctioned_amount=amount, interest_rate=rate,
                tenure_months=tenure, emi_amount=emi, disbursement_date=disbursement_date,
                first_emi_date=first_emi, maturity_date=maturity, loan_status=loan_status,
                closure_date=closure_date, risk_profile=risk_profile,
                months_elapsed=min(months_elapsed, tenure),
            )
            approved_loans.append(loan)

            loan_writer.add((
                loan_id, f"LN{loan_id:09d}", app_id, cust.customer_id, product["product_id"],
                branch_id, amount, amount, rate, tenure, emi, disbursement_date, first_emi,
                maturity, random.choice(BANK_NAMES), loan_status, closure_date, risk_profile,
                0, False,  # current_dpd / npa_flag finalized after schedule simulation (UPDATE pass)
            ))

    app_writer.flush()
    loan_writer.flush()
    log(f"loan_applications: {app_writer.total} rows")
    log(f"loans: {loan_writer.total} rows")
    return approved_loans


# Repayment behaviour is modelled as a 2-state Markov chain per loan
# ("current" <-> "delinquent") rather than independent-per-month coin
# flips: real delinquency is sticky (a borrower who falls behind tends to
# stay behind for a few months, not bounce back and forth randomly), and
# that stickiness is what actually produces 90+ DPD NPAs. p_default is the
# monthly hazard of a current loan slipping into delinquency; p_cure is the
# monthly chance a delinquent loan fully catches up and returns to current.
DELINQUENCY_PARAMS = {
    "Good":    dict(p_default=0.005, p_cure=0.55, late_given_current=0.06),
    "Average": dict(p_default=0.024, p_cure=0.35, late_given_current=0.16),
    "Risky":   dict(p_default=0.070, p_cure=0.17, late_given_current=0.30),
}


def simulate_and_write_schedule_collections(
    loans: list[dict], employee_ids_by_branch: dict, agent_ids_by_branch: dict, conn,
):
    sched_writer = CopyWriter(conn, "repayment_schedule", [
        "schedule_id", "loan_id", "installment_number", "due_date", "opening_principal",
        "principal_due", "interest_due", "emi_due", "closing_principal", "amount_paid",
        "paid_date", "payment_status", "dpd_days",
    ])
    coll_writer = CopyWriter(conn, "collections", [
        "collection_id", "receipt_number", "loan_id", "schedule_id", "customer_id",
        "collection_date", "principal_component", "interest_component", "penalty_component",
        "total_amount", "payment_mode", "collected_by_employee_id", "collected_by_agent_id",
    ], depends_on=[sched_writer])

    schedule_id = 0
    collection_id = 0
    loan_final_dpd: dict[int, int] = {}
    loan_npa_flag: dict[int, bool] = {}
    today = date(2026, 8, 22)

    for loan in loans:
        params = DELINQUENCY_PARAMS[loan["risk_profile"]]
        principal_remaining = float(loan["sanctioned_amount"])
        monthly_rate = loan["interest_rate"] / 12 / 100
        due_date = loan["first_emi_date"]
        emi = float(loan["emi_amount"])
        installments_to_simulate = loan["months_elapsed"] if loan["loan_status"] != "Active" else \
            min(loan["tenure_months"], max(1, (today.year - loan["disbursement_date"].year) * 12 +
                                            (today.month - loan["disbursement_date"].month)))
        simulated_installments: list[tuple[date, str]] = []  # (due_date, status) in order
        delinquent = False

        for inst_no in range(1, loan["tenure_months"] + 1):
            interest_due = round(principal_remaining * monthly_rate, 2)
            principal_due = round(min(emi - interest_due, principal_remaining), 2)
            if principal_due < 0:
                principal_due = 0
            emi_due = round(principal_due + interest_due, 2)
            closing_principal = round(max(principal_remaining - principal_due, 0), 2)

            schedule_id += 1
            this_sched_id = schedule_id

            if inst_no <= installments_to_simulate:
                just_defaulted = False
                if not delinquent and random.random() < params["p_default"]:
                    delinquent = True
                    just_defaulted = True

                if not delinquent:
                    if random.random() < params["late_given_current"]:
                        delay = random.randint(1, 20)
                        paid_date = due_date + timedelta(days=delay)
                        dpd = delay
                    else:
                        paid_date = due_date - timedelta(days=random.randint(0, 3))
                        dpd = 0
                    amount_paid = emi_due
                    status = "Paid"
                elif (not just_defaulted) and random.random() < params["p_cure"]:
                    # Catches up in full this month (collections applies
                    # the payment to clear the arrears too).
                    delinquent = False
                    paid_date = due_date + timedelta(days=random.randint(5, 25))
                    amount_paid = emi_due
                    status = "Paid"
                    dpd = (today - due_date).days if due_date < today else 0
                elif random.random() < 0.30:
                    paid_date = due_date + timedelta(days=random.randint(0, 20))
                    amount_paid = round(emi_due * random.uniform(0.3, 0.8), 2)
                    status = "Partially Paid"
                    dpd = max(0, (today - due_date).days)
                else:
                    paid_date = None
                    amount_paid = 0
                    status = "Overdue"
                    dpd = max(0, (today - due_date).days)

                simulated_installments.append((due_date, status))
            else:
                paid_date, amount_paid, status, dpd = None, 0, "Not Due", 0

            # The schedule row must be written (and, transitively, be safe
            # to flush) before any collection row references its
            # schedule_id - see CopyWriter.depends_on.
            sched_writer.add((
                this_sched_id, loan["loan_id"], inst_no, due_date, round(principal_remaining, 2),
                principal_due, interest_due, emi_due, closing_principal, amount_paid,
                paid_date, status, dpd,
            ))

            if inst_no <= installments_to_simulate and amount_paid > 0:
                collection_id += 1
                interest_component = min(amount_paid, interest_due)
                principal_component = round(amount_paid - interest_component, 2)
                penalty = round(min(50 + dpd * 2, 500), 2) if dpd > 0 else 0.0
                collected_by_employee_id = None
                collected_by_agent_id = None
                if random.random() < 0.5:
                    pool = employee_ids_by_branch.get(loan["branch_id"]) or []
                    if pool:
                        collected_by_employee_id = random.choice(pool)
                else:
                    pool = agent_ids_by_branch.get(loan["branch_id"]) or []
                    if pool:
                        collected_by_agent_id = random.choice(pool)
                coll_writer.add((
                    collection_id, f"RCP{collection_id:09d}", loan["loan_id"], this_sched_id,
                    loan["customer"].customer_id, paid_date, principal_component, interest_component,
                    penalty, round(amount_paid, 2), random.choice(PAYMENT_MODES),
                    collected_by_employee_id, collected_by_agent_id,
                ))

            principal_remaining = closing_principal
            due_date = (due_date.replace(day=1) + timedelta(days=32)).replace(day=min(loan["first_emi_date"].day, 28))

        # A loan's *current* delinquency is the unbroken run of unresolved
        # installments trailing at the end of its simulated life so far -
        # a later on-time/late payment is treated as the borrower catching
        # back up (collections applies it to clear the oldest arrear too),
        # not as ignoring history. Only an unbroken trailing streak still
        # open today keeps accruing DPD.
        current_dpd = 0
        if loan["loan_status"] == "Active":
            oldest_open_due_date = None
            for inst_due_date, inst_status in reversed(simulated_installments):
                if inst_status in ("Overdue", "Partially Paid"):
                    oldest_open_due_date = inst_due_date
                else:
                    break
            if oldest_open_due_date is not None and oldest_open_due_date < today:
                current_dpd = (today - oldest_open_due_date).days
        loan_final_dpd[loan["loan_id"]] = current_dpd
        loan_npa_flag[loan["loan_id"]] = current_dpd > 90

    sched_writer.flush()
    coll_writer.flush()
    log(f"repayment_schedule: {sched_writer.total} rows")
    log(f"collections: {coll_writer.total} rows")
    return loan_final_dpd, loan_npa_flag


def backfill_loan_dpd_and_npa(loan_final_dpd: dict, loan_npa_flag: dict, conn):
    log("Backfilling loans.current_dpd / npa_flag from simulated schedules...")
    rows = [(dpd, loan_npa_flag[lid], lid) for lid, dpd in loan_final_dpd.items()]
    with conn.cursor() as cur:
        psycopg2.extras.execute_batch(
            cur, "UPDATE loans SET current_dpd = %s, npa_flag = %s WHERE loan_id = %s", rows,
            page_size=5000,
        )
    conn.commit()


DPD_BUCKETS = [
    (0, 0, "Standard", "Standard", 0.0040),
    (1, 30, "SMA-0", "Standard", 0.0040),
    (31, 60, "SMA-1", "Standard", 0.0100),
    (61, 90, "SMA-2", "Standard", 0.1500),
    (91, 365, "NPA 91-365", "Sub-Standard", 0.2500),
    (366, 730, "NPA 1-2yr", "Doubtful", 0.5000),
    (731, 10_000, "NPA 2yr+", "Loss", 1.0000),
]


def bucket_for_dpd(dpd: int):
    for lo, hi, bucket, classification, prov in DPD_BUCKETS:
        if lo <= dpd <= hi:
            return bucket, classification, prov
    return DPD_BUCKETS[-1][2], DPD_BUCKETS[-1][3], DPD_BUCKETS[-1][4]


def generate_npa_classification(loans: list[dict], loan_final_dpd: dict, conn):
    writer = CopyWriter(conn, "npa_classification", [
        "npa_id", "loan_id", "as_of_date", "dpd_bucket", "asset_classification",
        "outstanding_principal", "provisioning_pct", "provisioning_amount",
    ])
    npa_id = 0
    as_of = date(2026, 8, 1)
    for loan in loans:
        if loan["loan_status"] != "Active":
            continue
        dpd = loan_final_dpd.get(loan["loan_id"], 0)
        if dpd <= 0 and random.random() > 0.15:
            continue  # skip most fully-standard loans; keep a sample for completeness
        bucket, classification, prov_pct = bucket_for_dpd(dpd)
        outstanding = round(float(loan["sanctioned_amount"]) * random.uniform(0.2, 0.95), 2)
        npa_id += 1
        writer.add((npa_id, loan["loan_id"], as_of, bucket, classification, outstanding,
                    prov_pct, round(outstanding * prov_pct, 2)))
    writer.flush()
    log(f"npa_classification: {writer.total} rows")


def generate_credit_bureau_records(customers: list[Customer], conn):
    writer = CopyWriter(conn, "credit_bureau_records", [
        "record_id", "customer_id", "bureau_name", "score", "report_date",
        "existing_loans_count", "total_outstanding", "enquiries_last_6m",
    ])
    record_id = 0
    bureaus = ["CIBIL", "Experian", "Equifax", "CRIF High Mark"]
    for cust in customers:
        n_records = 1 if random.random() < 0.75 else 2
        chosen_bureaus = random.sample(bureaus, k=n_records)
        for bureau in chosen_bureaus:
            record_id += 1
            score_variance = random.randint(-25, 25) if bureau != "CIBIL" else 0
            score = int(np.clip(cust.cibil + score_variance, 300, 900))
            report_date = random_date(date(2024, 1, 1), date(2026, 8, 20))
            writer.add((
                record_id, cust.customer_id, bureau, score, report_date,
                random.randint(0, 5), round(random.uniform(0, cust.income * 20), 2),
                random.randint(0, 8),
            ))
    writer.flush()
    log(f"credit_bureau_records: {writer.total} rows")


def generate_payables(loans: list[dict], branches: list[Branch], agent_ids_by_branch: dict, conn):
    writer = CopyWriter(conn, "payables", [
        "payable_id", "payable_type", "payee_name", "branch_id", "agent_id",
        "related_loan_id", "invoice_number", "amount", "due_date", "paid_date", "status",
    ])
    payable_id = 0
    today = date(2026, 8, 22)

    for loan in loans:
        if random.random() < 0.5:
            agent_pool = agent_ids_by_branch.get(loan["branch_id"]) or []
            if not agent_pool:
                continue
            payable_id += 1
            commission = round(float(loan["sanctioned_amount"]) * random.uniform(0.005, 0.02), 2)
            due = loan["disbursement_date"] + timedelta(days=30)
            paid = due + timedelta(days=random.randint(-5, 20)) if due < today else None
            writer.add((
                payable_id, "Agent Commission", "DSA Commission Payout", loan["branch_id"],
                random.choice(agent_pool), loan["loan_id"], f"INV{payable_id:08d}", commission,
                due, paid if paid and paid <= today else None,
                "Paid" if paid and paid <= today else "Pending",
            ))
        if random.random() < 0.15:
            payable_id += 1
            premium = round(float(loan["sanctioned_amount"]) * random.uniform(0.002, 0.01), 2)
            due = loan["disbursement_date"] + timedelta(days=15)
            paid = due + timedelta(days=random.randint(-3, 15)) if due < today else None
            writer.add((
                payable_id, "Insurance Premium", random.choice(INSURANCE_PARTNERS), None, None,
                loan["loan_id"], f"INV{payable_id:08d}", premium, due,
                paid if paid and paid <= today else None,
                "Paid" if paid and paid <= today else "Pending",
            ))

    # A handful of general vendor / branch operating expense payables, not loan-linked.
    vendor_types = ["Vendor Payment", "Employee Reimbursement", "Office Rent", "IT/Software AMC"]
    for _ in range(max(200, len(branches) * 15)):
        payable_id += 1
        b = random.choice(branches)
        due = random_date(date(2023, 1, 1), date(2026, 9, 30))
        paid = due + timedelta(days=random.randint(-5, 25))
        writer.add((
            payable_id, random.choice(vendor_types), fake.company(), b.branch_id, None, None,
            f"INV{payable_id:08d}", round(random.uniform(2_000, 500_000), 2), due,
            paid if paid <= today else None, "Paid" if paid <= today else "Pending",
        ))

    writer.flush()
    log(f"payables: {writer.total} rows")


def generate_ledger(loans: list[dict], conn):
    writer = CopyWriter(conn, "transactions_ledger", [
        "transaction_id", "reference_number", "loan_id", "customer_id", "transaction_type",
        "transaction_date", "amount", "payment_mode", "status",
    ])
    txn_id = 0
    for loan in loans:
        txn_id += 1
        writer.add((
            txn_id, f"TXN{txn_id:010d}", loan["loan_id"], loan["customer"].customer_id,
            "Disbursement", loan["disbursement_date"], float(loan["sanctioned_amount"]),
            "NEFT", "Success",
        ))
        fee = round(float(loan["sanctioned_amount"]) * loan["product"]["fee"] / 100, 2)
        txn_id += 1
        writer.add((
            txn_id, f"TXN{txn_id:010d}", loan["loan_id"], loan["customer"].customer_id,
            "Processing Fee", loan["disbursement_date"], fee, "Deducted at Disbursement", "Success",
        ))
    writer.flush()
    log(f"transactions_ledger (disbursement/fee entries): {writer.total} rows")


# --------------------------------------------------------------------------
# Main
# --------------------------------------------------------------------------

def main():
    parser = argparse.ArgumentParser(description="Generate the synthetic NBFC lending demo database.")
    parser.add_argument("--scale", choices=list(SCALE_PRESETS.keys()), default="full")
    parser.add_argument("--db-url", default=os.getenv("LENDING_DATABASE_URL", "postgresql://saarthi:password@localhost:5432/postgres"))
    parser.add_argument("--db-name", default="lending_demo_db")
    args = parser.parse_args()

    preset = SCALE_PRESETS[args.scale]
    log(f"Scale='{args.scale}' preset={preset}")

    ensure_database(args.db_url, args.db_name)
    target_url = derive_db_url(args.db_url, args.db_name)
    conn = psycopg2.connect(target_url)
    conn.autocommit = False

    t0 = time.time()
    with conn.cursor() as cur:
        log("Creating schema...")
        cur.execute(SCHEMA_SQL)
    conn.commit()

    branches = generate_branches(preset["branches"], conn)
    employee_ids_by_branch = generate_employees(preset["employees_per_branch"], branches, conn)
    agent_ids_by_branch = generate_agents(preset["agents"], branches, conn)
    products = generate_loan_products(conn)
    customers = generate_customers(preset["customers"], branches, conn)

    loans = generate_applications_and_loans(
        customers, products, employee_ids_by_branch, agent_ids_by_branch,
        preset["apps_per_customer"], conn,
    )

    loan_final_dpd, loan_npa_flag = simulate_and_write_schedule_collections(
        loans, employee_ids_by_branch, agent_ids_by_branch, conn,
    )
    backfill_loan_dpd_and_npa(loan_final_dpd, loan_npa_flag, conn)
    generate_npa_classification(loans, loan_final_dpd, conn)
    generate_credit_bureau_records(customers, conn)
    generate_payables(loans, branches, agent_ids_by_branch, conn)
    generate_ledger(loans, conn)

    log("Creating indexes...")
    with conn.cursor() as cur:
        cur.execute(INDEX_SQL)
    conn.commit()

    with conn.cursor() as cur:
        cur.execute("SELECT pg_size_pretty(pg_database_size(%s))", (args.db_name,))
        size = cur.fetchone()[0]

    elapsed = time.time() - t0
    log(f"Done in {elapsed:.1f}s. Database '{args.db_name}' size: {size}")
    conn.close()


if __name__ == "__main__":
    main()
