#!/usr/bin/env python3
"""
db_manufacturing.py
====================
Generates a realistic, synthetic manufacturing-company database (raw
material procurement -> shop-floor production -> quality inspection ->
dispatch/shipment -> payables -> machine downtime -> ledger) with Indian
supplier/customer data, for use as a demo/test data source inside Saarthi.

This is a self-contained companion project (data + a stub validation API +
Excel reference tables + factory policy docs live under
demo_manufacturing/) - it does not touch the main Saarthi Flask app's
models or logical databases; it provisions its own Postgres database and
can be registered as one more "database connection" data source inside
Saarthi once loaded.

ALL DATA IS SYNTHETIC. Names/companies are generated by Faker's en_IN
locale; GSTIN, mobile numbers, invoice numbers etc. are randomly generated
in the right *format* and are not real identifiers.

Usage
-----
    python db_manufacturing.py --scale small   # quick smoke test
    python db_manufacturing.py --scale medium
    python db_manufacturing.py --scale full     # default

    python db_manufacturing.py --scale full --db-url postgresql://user:pass@host:5432/postgres

Environment variables (used when --db-url is not given):
    MANUFACTURING_DATABASE_URL   base Postgres URL (server + credentials
                                  only; the database name itself is always
                                  "manufacturing_demo_db", created if missing)
                                  default: postgresql://saarthi:password@localhost:5432/postgres
"""

from __future__ import annotations

import argparse
import io
import os
import random
import time
from dataclasses import dataclass
from datetime import date, datetime, timedelta
from urllib.parse import urlparse

import numpy as np
import psycopg2
import psycopg2.extras
from faker import Faker
from psycopg2.extensions import ISOLATION_LEVEL_AUTOCOMMIT

# --------------------------------------------------------------------------
# Scale presets: row counts for the "base" master tables. Transaction-level
# tables (production_log, shipments, quality_inspection_records, ...) are
# derived from these, not set independently, so the whole dataset scales
# together and stays internally consistent.
# --------------------------------------------------------------------------
SCALE_PRESETS = {
    "tiny": dict(plants=4, employees_per_plant=6, suppliers=20, machines_per_plant=6,
                 customers=300, orders_per_customer=1.4),
    "small": dict(plants=10, employees_per_plant=9, suppliers=80, machines_per_plant=10,
                  customers=4_000, orders_per_customer=1.6),
    "medium": dict(plants=30, employees_per_plant=11, suppliers=350, machines_per_plant=13,
                   customers=25_000, orders_per_customer=1.9),
    "full": dict(plants=55, employees_per_plant=13, suppliers=750, machines_per_plant=16,
                 customers=55_000, orders_per_customer=2.1),
}

COPY_BATCH_ROWS = 50_000
RNG_SEED = 20260910  # fixed seed -> reproducible dataset across runs
TODAY = date(2026, 8, 25)

fake = Faker("en_IN")
Faker.seed(RNG_SEED)
random.seed(RNG_SEED)
np.random.seed(RNG_SEED)


# --------------------------------------------------------------------------
# Reference / lookup data
# --------------------------------------------------------------------------

# (city, state, a real-format pincode) - a representative spread of Indian
# metros, tier-2 and tier-3 towns/industrial belts, used for plant locations
# and, by extension, customer/supplier addresses.
INDIAN_CITIES = [
    ("Mumbai", "Maharashtra", "400001"), ("Pune", "Maharashtra", "411001"),
    ("Nagpur", "Maharashtra", "440001"), ("Nashik", "Maharashtra", "422001"),
    ("Aurangabad", "Maharashtra", "431001"), ("Delhi", "Delhi", "110001"),
    ("Bengaluru", "Karnataka", "560001"), ("Mysuru", "Karnataka", "570001"),
    ("Hubballi", "Karnataka", "580020"), ("Chennai", "Tamil Nadu", "600001"),
    ("Coimbatore", "Tamil Nadu", "641001"), ("Hosur", "Tamil Nadu", "635109"),
    ("Trichy", "Tamil Nadu", "620001"), ("Hyderabad", "Telangana", "500001"),
    ("Warangal", "Telangana", "506002"), ("Ahmedabad", "Gujarat", "380001"),
    ("Surat", "Gujarat", "395001"), ("Vadodara", "Gujarat", "390001"),
    ("Rajkot", "Gujarat", "360001"), ("Kolkata", "West Bengal", "700001"),
    ("Durgapur", "West Bengal", "713201"), ("Jaipur", "Rajasthan", "302001"),
    ("Jodhpur", "Rajasthan", "342001"), ("Bhiwadi", "Rajasthan", "301019"),
    ("Lucknow", "Uttar Pradesh", "226001"), ("Kanpur", "Uttar Pradesh", "208001"),
    ("Noida", "Uttar Pradesh", "201301"), ("Ghaziabad", "Uttar Pradesh", "201001"),
    ("Patna", "Bihar", "800001"), ("Bhopal", "Madhya Pradesh", "462001"),
    ("Indore", "Madhya Pradesh", "452001"), ("Pithampur", "Madhya Pradesh", "454775"),
    ("Chandigarh", "Chandigarh", "160001"), ("Ludhiana", "Punjab", "141001"),
    ("Jalandhar", "Punjab", "144001"), ("Bhubaneswar", "Odisha", "751001"),
    ("Cuttack", "Odisha", "753001"), ("Guwahati", "Assam", "781001"),
    ("Jamshedpur", "Jharkhand", "831001"), ("Raipur", "Chhattisgarh", "492001"),
    ("Bhilai", "Chhattisgarh", "490001"), ("Kochi", "Kerala", "682001"),
    ("Visakhapatnam", "Andhra Pradesh", "530001"), ("Vijayawada", "Andhra Pradesh", "520001"),
    ("Dehradun", "Uttarakhand", "248001"), ("Panaji", "Goa", "403001"),
    ("Gurugram", "Haryana", "122001"), ("Faridabad", "Haryana", "121001"),
    ("Manesar", "Haryana", "122051"), ("Rudrapur", "Uttarakhand", "263153"),
]

REGION_BY_STATE = {
    "Maharashtra": "West", "Gujarat": "West", "Goa": "West", "Rajasthan": "West",
    "Delhi": "North", "Punjab": "North", "Haryana": "North", "Uttar Pradesh": "North",
    "Uttarakhand": "North", "Chandigarh": "North",
    "Karnataka": "South", "Tamil Nadu": "South", "Kerala": "South", "Telangana": "South",
    "Andhra Pradesh": "South",
    "West Bengal": "East", "Odisha": "East", "Bihar": "East", "Jharkhand": "East",
    "Assam": "East",
    "Madhya Pradesh": "Central", "Chhattisgarh": "Central",
}

# Official 2-digit GST state codes, used only to format synthetic GSTINs in
# the right shape - not tied to any real registrant.
GST_STATE_CODES = {
    "Maharashtra": "27", "Delhi": "07", "Karnataka": "29", "Tamil Nadu": "33",
    "Telangana": "36", "Gujarat": "24", "West Bengal": "19", "Rajasthan": "08",
    "Uttar Pradesh": "09", "Bihar": "10", "Madhya Pradesh": "23", "Chandigarh": "04",
    "Punjab": "03", "Odisha": "21", "Assam": "18", "Jharkhand": "20",
    "Chhattisgarh": "22", "Kerala": "32", "Andhra Pradesh": "37",
    "Uttarakhand": "05", "Goa": "30", "Haryana": "06",
}

PLANT_TYPES = [
    "Machining", "Assembly", "Foundry", "Fabrication", "Injection Molding",
    "Sheet Metal Pressing", "Electronics Assembly",
]

EMPLOYEE_ROLES = [
    ("Plant Manager", 1), ("Production Supervisor", 3), ("Quality Inspector", 3),
    ("Machine Operator", 6), ("Maintenance Technician", 3), ("Store Keeper", 2),
    ("Safety Officer", 1), ("Logistics Coordinator", 2),
]

MACHINE_TYPES = [
    "CNC Lathe", "CNC Milling (VMC)", "Injection Molding Machine", "Press Brake",
    "Hydraulic Press", "Welding Robot", "Induction Furnace", "Surface Grinder",
    "Laser Cutting Machine", "Powder Coating Line", "Assembly Line Station", "Testing Rig",
]

MACHINE_MANUFACTURERS = [
    "Haas Automation", "DMG Mori", "Mazak", "BFW (Bharat Fritz Werner)", "Ace Micromatic",
    "HMT Machine Tools", "Amada", "Trumpf", "ABB Robotics", "KUKA",
]

MACHINE_STATUSES = [("Running", 0.70), ("Idle", 0.15), ("Under Maintenance", 0.08),
                     ("Breakdown", 0.05), ("Decommissioned", 0.02)]

# Finished-goods catalogue modeled on a typical Indian engineering/auto-components
# manufacturer's book (costs are illustrative, not any real manufacturer's card rates).
# code, name, category, uom, standard_cost, selling_price, min_order_qty, cycle_time_min
PRODUCTS = [
    ("BRK-CAL", "Brake Caliper Assembly", "Automotive Components", "PCS", 850.0, 1450.0, 500, 12.0),
    ("ENG-BRK", "Engine Mounting Bracket", "Automotive Components", "PCS", 220.0, 410.0, 1000, 6.5),
    ("GEAR-SH", "Precision Gear Shaft", "Machined Parts", "PCS", 640.0, 1150.0, 300, 18.0),
    ("HEX-BLT-M10", "Hex Bolt M10x50 (Grade 8.8)", "Industrial Fasteners", "PCS", 4.5, 9.0, 50_000, 0.15),
    ("HEX-NUT-M10", "Hex Nut M10", "Industrial Fasteners", "PCS", 1.8, 3.5, 50_000, 0.08),
    ("SHT-BRKT", "Sheet Metal Mounting Bracket", "Sheet Metal Assemblies", "PCS", 95.0, 175.0, 2_000, 3.2),
    ("ELE-ENCL", "Electrical Control Enclosure", "Electrical Enclosures", "PCS", 1350.0, 2400.0, 200, 25.0),
    ("PLST-HSG", "Plastic Connector Housing", "Plastic Molded Parts", "PCS", 12.0, 24.0, 20_000, 0.9),
    ("PLST-CVR", "Plastic Protective Cover", "Plastic Molded Parts", "PCS", 28.0, 52.0, 10_000, 1.4),
    ("HYD-CYL", "Hydraulic Cylinder Assembly", "Industrial Equipment", "PCS", 4200.0, 7500.0, 50, 45.0),
    ("VLV-BODY", "Valve Body Casting", "Foundry Castings", "PCS", 310.0, 560.0, 800, 22.0),
    ("PWR-CBL", "Power Cable Harness", "Wiring & Harnesses", "PCS", 145.0, 260.0, 1_500, 5.0),
]

# code, name, category, uom, standard_unit_price
RAW_MATERIALS = [
    ("STL-MS-SHT", "Mild Steel Sheet", "Steel", "KG", 62.0),
    ("STL-SS304", "Stainless Steel 304 Rod", "Steel", "KG", 240.0),
    ("ALU-6061", "Aluminium 6061 Billet", "Aluminum", "KG", 285.0),
    ("CU-WIRE", "Copper Wire (Enameled)", "Electrical", "KG", 780.0),
    ("PLST-ABS", "ABS Granules", "Plastic Resin", "KG", 145.0),
    ("PLST-PP", "Polypropylene Granules", "Plastic Resin", "KG", 110.0),
    ("FAST-HDW", "Fastener Hardware Kit", "Fasteners", "SET", 8.5),
    ("PAINT-EPX", "Epoxy Powder Coating", "Consumables", "KG", 320.0),
    ("BRG-SET", "Ball Bearing Set", "Components", "SET", 145.0),
    ("ELE-PCB", "Electronic PCB Module", "Electronic Components", "PCS", 210.0),
    ("RUBR-GKT", "Rubber Gasket Sheet", "Rubber & Sealing", "SQM", 480.0),
    ("PKG-CTN", "Corrugated Packaging Carton", "Packaging", "PCS", 22.0),
    ("LUB-OIL", "Industrial Lubricant Oil", "Consumables", "LTR", 195.0),
    ("WLD-ROD", "Welding Electrode Rod", "Consumables", "KG", 265.0),
    ("CST-IRON", "Cast Iron Ingot", "Foundry Raw", "KG", 58.0),
]

CUSTOMER_TYPES = [("OEM", 0.35), ("Tier-1 Supplier", 0.30), ("Distributor", 0.20),
                   ("Export Client", 0.10), ("Retail / Aftermarket", 0.05)]

PAYMENT_TERMS_DAYS = [15, 30, 45, 60, 90]

TRANSPORTERS = ["VRL Logistics", "TCI Express", "Safexpress", "Delhivery B2B",
                "Gati-KWE", "Blue Dart Freight", "DTDC Freight", "Own Fleet"]

TRANSPORT_MODES = [("Road", 0.82), ("Rail", 0.10), ("Air", 0.05), ("Sea", 0.03)]

PAYMENT_MODES = ["NEFT", "RTGS", "UPI", "Cheque", "Letter of Credit", "Cash"]


# --------------------------------------------------------------------------
# Small helpers
# --------------------------------------------------------------------------

def log(msg: str) -> None:
    print(f"[{datetime.now().strftime('%H:%M:%S')}] {msg}", flush=True)


def derive_db_url(base_url: str, db_name: str) -> str:
    parsed = urlparse(base_url)
    return parsed._replace(path=f"/{db_name}").geturl()


def gen_pan() -> str:
    letters1 = "".join(random.choices("ABCDEFGHIJKLMNOPQRSTUVWXYZ", k=5))
    digits = "".join(random.choices("0123456789", k=4))
    letter2 = random.choice("ABCDEFGHIJKLMNOPQRSTUVWXYZ")
    return f"{letters1}{digits}{letter2}"


def gen_gstin(state: str) -> str:
    state_code = GST_STATE_CODES.get(state, "27")
    pan = gen_pan()
    entity_code = random.choice("123456789")
    checksum = random.choice("0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ")
    return f"{state_code}{pan}{entity_code}Z{checksum}"


def gen_mobile() -> str:
    first = random.choice("6789")
    rest = "".join(random.choices("0123456789", k=9))
    return f"+91{first}{rest}"


def weighted_choice(pairs):
    values, weights = zip(*pairs)
    return random.choices(values, weights=weights, k=1)[0]


def random_date(start: date, end: date) -> date:
    delta_days = (end - start).days
    if delta_days <= 0:
        return start
    return start + timedelta(days=random.randint(0, delta_days))


def add_working_day(d: date) -> date:
    """Advance one calendar day, skipping Sundays (6-day work week)."""
    nd = d + timedelta(days=1)
    if nd.weekday() == 6:  # Sunday
        nd += timedelta(days=1)
    return nd


# --------------------------------------------------------------------------
# Schema
# --------------------------------------------------------------------------

SCHEMA_SQL = """
DROP TABLE IF EXISTS transactions_ledger CASCADE;
DROP TABLE IF EXISTS quality_inspection_records CASCADE;
DROP TABLE IF EXISTS machine_downtime CASCADE;
DROP TABLE IF EXISTS payables CASCADE;
DROP TABLE IF EXISTS shipments CASCADE;
DROP TABLE IF EXISTS production_log CASCADE;
DROP TABLE IF EXISTS production_orders CASCADE;
DROP TABLE IF EXISTS purchase_orders CASCADE;
DROP TABLE IF EXISTS bill_of_materials CASCADE;
DROP TABLE IF EXISTS customers CASCADE;
DROP TABLE IF EXISTS raw_materials CASCADE;
DROP TABLE IF EXISTS products CASCADE;
DROP TABLE IF EXISTS machines CASCADE;
DROP TABLE IF EXISTS suppliers CASCADE;
DROP TABLE IF EXISTS employees CASCADE;
DROP TABLE IF EXISTS plants CASCADE;

CREATE TABLE plants (
    plant_id        INTEGER PRIMARY KEY,
    plant_code      VARCHAR(10) UNIQUE NOT NULL,
    plant_name      VARCHAR(120) NOT NULL,
    city            VARCHAR(80) NOT NULL,
    state           VARCHAR(80) NOT NULL,
    pincode         VARCHAR(6) NOT NULL,
    region          VARCHAR(20) NOT NULL,
    plant_type      VARCHAR(30) NOT NULL,
    opened_date     DATE NOT NULL,
    is_active       BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE TABLE employees (
    employee_id     INTEGER PRIMARY KEY,
    employee_code   VARCHAR(15) UNIQUE NOT NULL,
    plant_id        INTEGER NOT NULL REFERENCES plants(plant_id),
    full_name       VARCHAR(120) NOT NULL,
    designation     VARCHAR(40) NOT NULL,
    email           VARCHAR(120),
    mobile          VARCHAR(15),
    date_joined     DATE NOT NULL,
    is_active       BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE TABLE suppliers (
    supplier_id     INTEGER PRIMARY KEY,
    supplier_code   VARCHAR(15) UNIQUE NOT NULL,
    supplier_name   VARCHAR(120) NOT NULL,
    company_name    VARCHAR(150),
    plant_id        INTEGER NOT NULL REFERENCES plants(plant_id),
    mobile          VARCHAR(15),
    gstin           VARCHAR(15),
    quality_rating  NUMERIC(3,1) NOT NULL,
    empanelled_date DATE NOT NULL,
    is_active       BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE TABLE machines (
    machine_id              INTEGER PRIMARY KEY,
    machine_code            VARCHAR(15) UNIQUE NOT NULL,
    machine_name            VARCHAR(120) NOT NULL,
    machine_type            VARCHAR(40) NOT NULL,
    plant_id                INTEGER NOT NULL REFERENCES plants(plant_id),
    manufacturer            VARCHAR(80),
    installed_date          DATE NOT NULL,
    capacity_units_per_hour NUMERIC(10,2) NOT NULL,
    status                  VARCHAR(20) NOT NULL
);

CREATE TABLE products (
    product_id          SMALLINT PRIMARY KEY,
    product_code        VARCHAR(15) UNIQUE NOT NULL,
    product_name        VARCHAR(120) NOT NULL,
    category            VARCHAR(40) NOT NULL,
    unit_of_measure     VARCHAR(10) NOT NULL,
    standard_cost       NUMERIC(12,2) NOT NULL,
    selling_price       NUMERIC(12,2) NOT NULL,
    min_order_qty       INTEGER NOT NULL,
    standard_cycle_time_minutes NUMERIC(8,2) NOT NULL
);

CREATE TABLE raw_materials (
    material_id         SMALLINT PRIMARY KEY,
    material_code       VARCHAR(15) UNIQUE NOT NULL,
    material_name       VARCHAR(120) NOT NULL,
    category            VARCHAR(40) NOT NULL,
    unit_of_measure     VARCHAR(10) NOT NULL,
    standard_unit_price NUMERIC(12,2) NOT NULL
);

CREATE TABLE bill_of_materials (
    bom_id              INTEGER PRIMARY KEY,
    product_id          SMALLINT NOT NULL REFERENCES products(product_id),
    material_id         SMALLINT NOT NULL REFERENCES raw_materials(material_id),
    quantity_per_unit   NUMERIC(10,3) NOT NULL
);

CREATE TABLE customers (
    customer_id         INTEGER PRIMARY KEY,
    customer_code       VARCHAR(15) UNIQUE NOT NULL,
    company_name        VARCHAR(150) NOT NULL,
    contact_person      VARCHAR(120) NOT NULL,
    gstin               VARCHAR(15),
    mobile              VARCHAR(15) NOT NULL,
    email               VARCHAR(120),
    address_line        VARCHAR(160),
    city                VARCHAR(80) NOT NULL,
    state               VARCHAR(80) NOT NULL,
    pincode             VARCHAR(6) NOT NULL,
    customer_type       VARCHAR(25) NOT NULL,
    credit_limit        NUMERIC(14,2) NOT NULL,
    payment_terms_days  SMALLINT NOT NULL,
    home_plant_id       INTEGER NOT NULL REFERENCES plants(plant_id),
    onboarded_date      DATE NOT NULL
);

CREATE TABLE purchase_orders (
    po_id                   BIGINT PRIMARY KEY,
    po_number               VARCHAR(20) UNIQUE NOT NULL,
    supplier_id             INTEGER NOT NULL REFERENCES suppliers(supplier_id),
    material_id             SMALLINT NOT NULL REFERENCES raw_materials(material_id),
    plant_id                INTEGER NOT NULL REFERENCES plants(plant_id),
    requested_by_employee_id INTEGER REFERENCES employees(employee_id),
    order_date              DATE NOT NULL,
    quantity                NUMERIC(14,2) NOT NULL,
    unit_price              NUMERIC(12,2) NOT NULL,
    total_amount            NUMERIC(14,2) NOT NULL,
    status                  VARCHAR(20) NOT NULL,
    rejection_reason        VARCHAR(120),
    expected_delivery_date  DATE,
    received_date           DATE
);

CREATE TABLE production_orders (
    production_order_id    BIGINT PRIMARY KEY,
    order_number            VARCHAR(20) UNIQUE NOT NULL,
    customer_id             INTEGER NOT NULL REFERENCES customers(customer_id),
    product_id              SMALLINT NOT NULL REFERENCES products(product_id),
    plant_id                INTEGER NOT NULL REFERENCES plants(plant_id),
    machine_id               INTEGER REFERENCES machines(machine_id),
    supervisor_employee_id  INTEGER REFERENCES employees(employee_id),
    order_date               DATE NOT NULL,
    quantity_ordered          INTEGER NOT NULL,
    unit_price                NUMERIC(12,2) NOT NULL,
    total_order_value         NUMERIC(14,2) NOT NULL,
    planned_start_date        DATE,
    planned_end_date          DATE,
    actual_start_date         DATE,
    actual_end_date           DATE,
    quantity_produced          INTEGER NOT NULL DEFAULT 0,
    quantity_rejected          INTEGER NOT NULL DEFAULT 0,
    order_status               VARCHAR(20) NOT NULL,
    priority                   VARCHAR(10) NOT NULL,
    reliability_profile         VARCHAR(10) NOT NULL,
    delay_days                  INTEGER NOT NULL DEFAULT 0,
    at_risk_flag                BOOLEAN NOT NULL DEFAULT FALSE
);

CREATE TABLE production_log (
    log_id                  BIGINT PRIMARY KEY,
    production_order_id     BIGINT NOT NULL REFERENCES production_orders(production_order_id),
    log_date                DATE NOT NULL,
    shift                   VARCHAR(10) NOT NULL,
    planned_qty             INTEGER NOT NULL,
    produced_qty            INTEGER NOT NULL DEFAULT 0,
    rejected_qty            INTEGER NOT NULL DEFAULT 0,
    machine_id              INTEGER REFERENCES machines(machine_id),
    operator_employee_id    INTEGER REFERENCES employees(employee_id),
    downtime_minutes        INTEGER NOT NULL DEFAULT 0,
    log_status               VARCHAR(20) NOT NULL
);

CREATE TABLE shipments (
    shipment_id             BIGINT PRIMARY KEY,
    shipment_number         VARCHAR(20) UNIQUE NOT NULL,
    production_order_id     BIGINT NOT NULL REFERENCES production_orders(production_order_id),
    customer_id             INTEGER NOT NULL REFERENCES customers(customer_id),
    plant_id                INTEGER NOT NULL REFERENCES plants(plant_id),
    shipment_date            DATE NOT NULL,
    quantity_shipped          INTEGER NOT NULL,
    unit_price                 NUMERIC(12,2) NOT NULL,
    freight_amount              NUMERIC(12,2) NOT NULL DEFAULT 0,
    total_invoice_amount        NUMERIC(14,2) NOT NULL,
    transporter                  VARCHAR(80),
    transport_mode                VARCHAR(15) NOT NULL,
    shipment_status                VARCHAR(15) NOT NULL,
    delivered_date                  DATE,
    dispatched_by_employee_id       INTEGER REFERENCES employees(employee_id)
);

CREATE TABLE payables (
    payable_id          BIGINT PRIMARY KEY,
    payable_type        VARCHAR(30) NOT NULL,
    payee_name          VARCHAR(150) NOT NULL,
    plant_id            INTEGER REFERENCES plants(plant_id),
    supplier_id         INTEGER REFERENCES suppliers(supplier_id),
    related_po_id       BIGINT REFERENCES purchase_orders(po_id),
    invoice_number      VARCHAR(25) UNIQUE NOT NULL,
    amount              NUMERIC(14,2) NOT NULL,
    due_date            DATE NOT NULL,
    paid_date           DATE,
    status              VARCHAR(15) NOT NULL
);

CREATE TABLE machine_downtime (
    downtime_id         BIGINT PRIMARY KEY,
    machine_id          INTEGER NOT NULL REFERENCES machines(machine_id),
    as_of_date          DATE NOT NULL,
    downtime_category   VARCHAR(25) NOT NULL,
    downtime_hours      NUMERIC(8,2) NOT NULL,
    maintenance_cost    NUMERIC(12,2) NOT NULL,
    criticality         VARCHAR(10) NOT NULL
);

CREATE TABLE quality_inspection_records (
    inspection_id           BIGINT PRIMARY KEY,
    production_order_id     BIGINT NOT NULL REFERENCES production_orders(production_order_id),
    product_id              SMALLINT NOT NULL REFERENCES products(product_id),
    inspection_date          DATE NOT NULL,
    inspector_employee_id    INTEGER REFERENCES employees(employee_id),
    inspection_stage          VARCHAR(20) NOT NULL,
    sample_size                 INTEGER NOT NULL,
    defects_found                INTEGER NOT NULL,
    defect_rate_pct               NUMERIC(5,2) NOT NULL,
    result                         VARCHAR(10) NOT NULL
);

CREATE TABLE transactions_ledger (
    transaction_id      BIGINT PRIMARY KEY,
    reference_number    VARCHAR(25) UNIQUE NOT NULL,
    production_order_id BIGINT REFERENCES production_orders(production_order_id),
    customer_id         INTEGER REFERENCES customers(customer_id),
    transaction_type    VARCHAR(25) NOT NULL,
    transaction_date    DATE NOT NULL,
    amount              NUMERIC(14,2) NOT NULL,
    payment_mode        VARCHAR(30) NOT NULL,
    status               VARCHAR(15) NOT NULL
);
"""

INDEX_SQL = """
CREATE INDEX idx_employees_plant ON employees(plant_id);
CREATE INDEX idx_suppliers_plant ON suppliers(plant_id);
CREATE INDEX idx_machines_plant ON machines(plant_id);
CREATE INDEX idx_customers_plant ON customers(home_plant_id);
CREATE INDEX idx_bom_product ON bill_of_materials(product_id);
CREATE INDEX idx_po_supplier ON purchase_orders(supplier_id);
CREATE INDEX idx_po_status ON purchase_orders(status);
CREATE INDEX idx_po_plant ON purchase_orders(plant_id);
CREATE INDEX idx_prod_orders_customer ON production_orders(customer_id);
CREATE INDEX idx_prod_orders_product ON production_orders(product_id);
CREATE INDEX idx_prod_orders_status ON production_orders(order_status);
CREATE INDEX idx_prod_orders_at_risk ON production_orders(at_risk_flag);
CREATE INDEX idx_prod_log_order ON production_log(production_order_id);
CREATE INDEX idx_prod_log_date ON production_log(log_date);
CREATE INDEX idx_prod_log_status ON production_log(log_status);
CREATE INDEX idx_shipments_order ON shipments(production_order_id);
CREATE INDEX idx_shipments_customer ON shipments(customer_id);
CREATE INDEX idx_shipments_date ON shipments(shipment_date);
CREATE INDEX idx_payables_status ON payables(status);
CREATE INDEX idx_payables_supplier ON payables(supplier_id);
CREATE INDEX idx_downtime_machine ON machine_downtime(machine_id);
CREATE INDEX idx_inspection_order ON quality_inspection_records(production_order_id);
CREATE INDEX idx_ledger_order ON transactions_ledger(production_order_id);
CREATE INDEX idx_ledger_date ON transactions_ledger(transaction_date);
CREATE INDEX idx_ledger_type ON transactions_ledger(transaction_type);
"""


def ensure_database(base_url: str, db_name: str) -> None:
    parsed = urlparse(base_url)
    maint_conn = psycopg2.connect(
        dbname="postgres", user=parsed.username, password=parsed.password,
        host=parsed.hostname, port=parsed.port or 5432,
    )
    maint_conn.set_isolation_level(ISOLATION_LEVEL_AUTOCOMMIT)
    try:
        with maint_conn.cursor() as cur:
            cur.execute("SELECT 1 FROM pg_database WHERE datname = %s", (db_name,))
            if not cur.fetchone():
                log(f"Creating database '{db_name}'...")
                cur.execute(f'CREATE DATABASE "{db_name}"')
            else:
                log(f"Database '{db_name}' already exists - will be reset (schema DROP/CREATE).")
    finally:
        maint_conn.close()


class CopyWriter:
    """Buffers rows for one table and flushes them via COPY in batches."""

    def __init__(self, conn, table: str, columns: list[str], depends_on: list["CopyWriter"] | None = None):
        self.conn = conn
        self.table = table
        self.columns = columns
        self.buffer = io.StringIO()
        self.count_in_buffer = 0
        self.total = 0
        # Writers for tables this one holds foreign keys into. Flushed
        # before this writer's own buffer so a row can never reference an
        # id that hasn't actually been COPY'd (and committed) yet.
        self.depends_on = depends_on or []

    @staticmethod
    def _fmt(value) -> str:
        if value is None:
            return r"\N"
        if isinstance(value, bool):
            return "t" if value else "f"
        if isinstance(value, (date, datetime)):
            return value.isoformat()
        if isinstance(value, str):
            return value.replace("\\", "\\\\").replace("\t", "\\t").replace("\n", "\\n").replace("\r", "")
        return str(value)

    def add(self, row: tuple) -> None:
        self.buffer.write("\t".join(self._fmt(v) for v in row))
        self.buffer.write("\n")
        self.count_in_buffer += 1
        if self.count_in_buffer >= COPY_BATCH_ROWS:
            self.flush()

    def flush(self) -> None:
        for dep in self.depends_on:
            dep.flush()
        if self.count_in_buffer == 0:
            return
        self.buffer.seek(0)
        with self.conn.cursor() as cur:
            cur.copy_expert(
                f"COPY {self.table} ({', '.join(self.columns)}) FROM STDIN WITH (FORMAT text)",
                self.buffer,
            )
        self.conn.commit()
        self.total += self.count_in_buffer
        self.buffer = io.StringIO()
        self.count_in_buffer = 0


# --------------------------------------------------------------------------
# Generators
# --------------------------------------------------------------------------

@dataclass
class Plant:
    plant_id: int
    city: str
    state: str
    pincode: str
    region: str
    plant_type: str


@dataclass
class Machine:
    machine_id: int
    plant_id: int
    machine_type: str


@dataclass
class Supplier:
    supplier_id: int
    plant_id: int


@dataclass
class Customer:
    customer_id: int
    plant_id: int
    city: str
    state: str
    pincode: str
    credit_limit: float
    customer_type: str


def generate_plants(n: int, conn) -> list[Plant]:
    writer = CopyWriter(conn, "plants", [
        "plant_id", "plant_code", "plant_name", "city", "state", "pincode",
        "region", "plant_type", "opened_date", "is_active",
    ])
    plants = []
    cities_cycle = (INDIAN_CITIES * (n // len(INDIAN_CITIES) + 1))[:n]
    random.shuffle(cities_cycle)
    for i, (city, state, pincode) in enumerate(cities_cycle, start=1):
        region = REGION_BY_STATE.get(state, "Central")
        plant_type = random.choice(PLANT_TYPES)
        opened = random_date(date(2005, 1, 1), date(2024, 6, 30))
        code = f"PLT{i:04d}"
        name = f"{city} {plant_type} Plant {i}"
        writer.add((i, code, name, city, state, pincode, region, plant_type, opened, True))
        plants.append(Plant(i, city, state, pincode, region, plant_type))
    writer.flush()
    log(f"plants: {writer.total} rows")
    return plants


def generate_employees(n_per_plant: int, plants: list[Plant], conn) -> dict[int, list[int]]:
    writer = CopyWriter(conn, "employees", [
        "employee_id", "employee_code", "plant_id", "full_name", "designation",
        "email", "mobile", "date_joined", "is_active",
    ])
    employee_ids_by_plant: dict[int, list[int]] = {p.plant_id: [] for p in plants}
    eid = 0
    for p in plants:
        roles = []
        for role, count in EMPLOYEE_ROLES:
            roles += [role] * count
        random.shuffle(roles)
        for role in roles[:n_per_plant] if n_per_plant < len(roles) else roles:
            eid += 1
            name = fake.name()
            joined = random_date(date(2008, 1, 1), date(2025, 12, 31))
            email = f"{name.lower().replace(' ', '.')}{eid}@precisionforge.in"
            writer.add((eid, f"EMP{eid:06d}", p.plant_id, name, role, email, gen_mobile(), joined, True))
            employee_ids_by_plant[p.plant_id].append(eid)
    writer.flush()
    log(f"employees: {writer.total} rows")
    return employee_ids_by_plant


def generate_suppliers(n: int, plants: list[Plant], conn) -> list[Supplier]:
    writer = CopyWriter(conn, "suppliers", [
        "supplier_id", "supplier_code", "supplier_name", "company_name", "plant_id",
        "mobile", "gstin", "quality_rating", "empanelled_date", "is_active",
    ])
    suppliers = []
    for i in range(1, n + 1):
        p = random.choice(plants)
        name = fake.name()
        company = fake.company()
        empanelled = random_date(date(2010, 1, 1), date(2025, 12, 31))
        writer.add((i, f"SUP{i:06d}", name, company, p.plant_id, gen_mobile(),
                    gen_gstin(p.state), round(random.uniform(2.0, 5.0), 1), empanelled,
                    random.random() > 0.05))
        suppliers.append(Supplier(i, p.plant_id))
    writer.flush()
    log(f"suppliers: {writer.total} rows")
    return suppliers


def generate_machines(n_per_plant: int, plants: list[Plant], conn) -> tuple[list[Machine], dict[int, list[int]]]:
    writer = CopyWriter(conn, "machines", [
        "machine_id", "machine_code", "machine_name", "machine_type", "plant_id",
        "manufacturer", "installed_date", "capacity_units_per_hour", "status",
    ])
    machines = []
    machine_ids_by_plant: dict[int, list[int]] = {p.plant_id: [] for p in plants}
    mid = 0
    for p in plants:
        for _ in range(n_per_plant):
            mid += 1
            mtype = random.choice(MACHINE_TYPES)
            installed = random_date(date(2008, 1, 1), date(2025, 6, 30))
            status = weighted_choice(MACHINE_STATUSES)
            writer.add((
                mid, f"MCH{mid:06d}", f"{mtype} #{mid}", mtype, p.plant_id,
                random.choice(MACHINE_MANUFACTURERS), installed,
                round(random.uniform(20, 400), 2), status,
            ))
            machines.append(Machine(mid, p.plant_id, mtype))
            machine_ids_by_plant[p.plant_id].append(mid)
    writer.flush()
    log(f"machines: {writer.total} rows")
    return machines, machine_ids_by_plant


def generate_products(conn) -> list[dict]:
    writer = CopyWriter(conn, "products", [
        "product_id", "product_code", "product_name", "category", "unit_of_measure",
        "standard_cost", "selling_price", "min_order_qty", "standard_cycle_time_minutes",
    ])
    products = []
    for i, p in enumerate(PRODUCTS, start=1):
        code, name, category, uom, cost, price, moq, cycle = p
        writer.add((i, code, name, category, uom, cost, price, moq, cycle))
        products.append(dict(product_id=i, code=code, name=name, category=category, uom=uom,
                              cost=cost, price=price, moq=moq, cycle_time=cycle))
    writer.flush()
    log(f"products: {writer.total} rows")
    return products


def generate_raw_materials(conn) -> list[dict]:
    writer = CopyWriter(conn, "raw_materials", [
        "material_id", "material_code", "material_name", "category", "unit_of_measure",
        "standard_unit_price",
    ])
    materials = []
    for i, m in enumerate(RAW_MATERIALS, start=1):
        code, name, category, uom, price = m
        writer.add((i, code, name, category, uom, price))
        materials.append(dict(material_id=i, code=code, name=name, category=category,
                               uom=uom, price=price))
    writer.flush()
    log(f"raw_materials: {writer.total} rows")
    return materials


def generate_bom(products: list[dict], materials: list[dict], conn) -> None:
    writer = CopyWriter(conn, "bill_of_materials", [
        "bom_id", "product_id", "material_id", "quantity_per_unit",
    ])
    bom_id = 0
    for p in products:
        chosen = random.sample(materials, k=random.randint(2, 5))
        for m in chosen:
            bom_id += 1
            writer.add((bom_id, p["product_id"], m["material_id"], round(random.uniform(0.02, 5.0), 3)))
    writer.flush()
    log(f"bill_of_materials: {writer.total} rows")


def generate_customers(n: int, plants: list[Plant], conn) -> list[Customer]:
    writer = CopyWriter(conn, "customers", [
        "customer_id", "customer_code", "company_name", "contact_person", "gstin",
        "mobile", "email", "address_line", "city", "state", "pincode", "customer_type",
        "credit_limit", "payment_terms_days", "home_plant_id", "onboarded_date",
    ])
    customers = []
    for i in range(1, n + 1):
        p = random.choice(plants)
        company = fake.company()
        contact = fake.name()
        ctype = weighted_choice(CUSTOMER_TYPES)
        if ctype == "OEM":
            credit_limit = max(500_000, np.random.lognormal(mean=14.5, sigma=0.6))
        elif ctype == "Export Client":
            credit_limit = max(300_000, np.random.lognormal(mean=14.0, sigma=0.7))
        elif ctype == "Tier-1 Supplier":
            credit_limit = max(200_000, np.random.lognormal(mean=13.5, sigma=0.6))
        else:
            credit_limit = max(50_000, np.random.lognormal(mean=12.0, sigma=0.7))
        onboarded = random_date(date(2015, 1, 1), TODAY - timedelta(days=1))
        email = f"{contact.lower().replace(' ', '.')}{i}@example.com" if random.random() > 0.1 else None
        writer.add((
            i, f"CUS{i:07d}", company, contact, gen_gstin(p.state), gen_mobile(), email,
            fake.street_address(), p.city, p.state, p.pincode, ctype,
            round(float(credit_limit), 2), random.choice(PAYMENT_TERMS_DAYS),
            p.plant_id, onboarded,
        ))
        customers.append(Customer(i, p.plant_id, p.city, p.state, p.pincode,
                                   float(credit_limit), ctype))
    writer.flush()
    log(f"customers: {writer.total} rows")
    return customers


def generate_purchase_orders(
    suppliers: list[Supplier], materials: list[dict],
    employee_ids_by_plant: dict, conn,
) -> list[dict]:
    writer = CopyWriter(conn, "purchase_orders", [
        "po_id", "po_number", "supplier_id", "material_id", "plant_id",
        "requested_by_employee_id", "order_date", "quantity", "unit_price", "total_amount",
        "status", "rejection_reason", "expected_delivery_date", "received_date",
    ])
    po_id = 0
    received_pos = []
    for s in suppliers:
        n_po = np.random.poisson(4) or 1
        for _ in range(n_po):
            po_id += 1
            material = random.choice(materials)
            order_date = random_date(date(2019, 1, 1), TODAY - timedelta(days=2))
            quantity = round(random.uniform(100, 20_000), 2)
            unit_price = round(material["price"] * random.uniform(0.9, 1.15), 2)
            total = round(quantity * unit_price, 2)
            status = weighted_choice([
                ("Received", 0.78), ("Approved", 0.08), ("Cancelled", 0.05),
                ("Rejected", 0.05), ("Draft", 0.04),
            ])
            expected_delivery = order_date + timedelta(days=random.randint(5, 30))
            received_date = None
            rejection_reason = None
            if status == "Received":
                received_date = min(expected_delivery + timedelta(days=random.randint(-3, 12)), TODAY)
            elif status == "Rejected":
                rejection_reason = random.choice([
                    "Quality certificate not provided", "Price above approved rate contract",
                    "Delivery lead time unacceptable", "Vendor capacity insufficient",
                ])
            pool = employee_ids_by_plant.get(s.plant_id) or []
            requester = random.choice(pool) if pool else None
            writer.add((
                po_id, f"PO{po_id:08d}", s.supplier_id, material["material_id"], s.plant_id,
                requester, order_date, quantity, unit_price, total, status, rejection_reason,
                expected_delivery, received_date,
            ))
            if status == "Received":
                received_pos.append(dict(po_id=po_id, supplier_id=s.supplier_id, plant_id=s.plant_id,
                                          total_amount=total, received_date=received_date))
    writer.flush()
    log(f"purchase_orders: {writer.total} rows")
    return received_pos


# Reliability profile mix drives shop-floor disruption behaviour downstream.
RELIABILITY_PROFILES = [("Good", 0.60), ("Average", 0.30), ("Poor", 0.10)]
RELIABILITY_PARAMS = {
    "Good":    dict(p_disruption=0.03, p_recovery=0.60, reject_rate=0.010),
    "Average": dict(p_disruption=0.08, p_recovery=0.40, reject_rate=0.030),
    "Poor":    dict(p_disruption=0.16, p_recovery=0.22, reject_rate=0.070),
}
ORDER_ACCEPT_WEIGHTS = [("Accepted", 0.90), ("Rejected", 0.06), ("Cancelled", 0.04)]
REJECTION_REASONS = [
    "Customer credit limit exceeded", "Machine capacity unavailable in requested window",
    "Raw material lead time conflict", "Specification could not be met",
    "Customer over 90 days overdue on existing invoices",
]


@dataclass
class ProdOrder:
    production_order_id: int
    customer: Customer
    product: dict
    plant_id: int
    machine_id: int | None
    quantity_ordered: int
    unit_price: float
    order_date: date
    planned_start_date: date
    planned_end_date: date
    planned_days: int
    reliability_profile: str
    target_status: str  # Completed / In Progress / Delayed / On Hold


def generate_production_orders(
    customers: list[Customer], products: list[dict], plants: list[Plant],
    machine_ids_by_plant: dict, employee_ids_by_plant: dict,
    orders_per_customer: float, conn,
) -> tuple["CopyWriter", list[ProdOrder]]:
    writer = CopyWriter(conn, "production_orders", [
        "production_order_id", "order_number", "customer_id", "product_id", "plant_id",
        "machine_id", "supervisor_employee_id", "order_date", "quantity_ordered", "unit_price",
        "total_order_value", "planned_start_date", "planned_end_date", "actual_start_date",
        "actual_end_date", "quantity_produced", "quantity_rejected", "order_status", "priority",
        "reliability_profile", "delay_days", "at_risk_flag",
    ])
    order_id = 0
    active_orders: list[ProdOrder] = []

    for cust in customers:
        n_orders = np.random.poisson(orders_per_customer) or 1
        for _ in range(n_orders):
            order_id += 1
            product = random.choice(products)
            plant_id = cust.plant_id
            accept = weighted_choice(ORDER_ACCEPT_WEIGHTS)
            quantity_ordered = int(round(random.uniform(product["moq"], product["moq"] * 12)))
            unit_price = round(product["price"] * random.uniform(0.95, 1.1), 2)
            total_value = round(quantity_ordered * unit_price, 2)
            shift_capacity_per_day = max(1, round(8 * 60 / product["cycle_time"]))
            planned_days = max(2, min(120, -(-quantity_ordered // shift_capacity_per_day)))
            priority = weighted_choice([("Low", 0.20), ("Normal", 0.55), ("High", 0.20), ("Urgent", 0.05)])

            if accept != "Accepted":
                order_date = random_date(date(2019, 1, 1), TODAY - timedelta(days=5))
                writer.add((
                    order_id, f"PROD{order_id:08d}", cust.customer_id, product["product_id"], plant_id,
                    None, None, order_date, quantity_ordered, unit_price, total_value,
                    None, None, None, None, 0, 0,
                    accept, priority, weighted_choice(RELIABILITY_PROFILES), 0, False,
                ))
                continue

            target_status = weighted_choice([
                ("Completed", 0.58), ("In Progress", 0.18), ("Delayed", 0.12),
                ("On Hold", 0.07), ("Cancelled", 0.05),
            ])
            if target_status in ("In Progress", "Delayed", "On Hold"):
                order_date = random_date(TODAY - timedelta(days=150), TODAY - timedelta(days=15))
            else:
                order_date = random_date(date(2019, 1, 1), TODAY - timedelta(days=planned_days + 20))

            planned_start = order_date + timedelta(days=random.randint(2, 10))
            planned_end = planned_start + timedelta(days=planned_days)
            machine_pool = machine_ids_by_plant.get(plant_id) or []
            machine_id = random.choice(machine_pool) if machine_pool else None
            supervisor_pool = employee_ids_by_plant.get(plant_id) or []
            supervisor_id = random.choice(supervisor_pool) if supervisor_pool else None
            reliability_profile = weighted_choice(RELIABILITY_PROFILES)

            active_orders.append(ProdOrder(
                production_order_id=order_id, customer=cust, product=product, plant_id=plant_id,
                machine_id=machine_id, quantity_ordered=quantity_ordered, unit_price=unit_price,
                order_date=order_date, planned_start_date=planned_start, planned_end_date=planned_end,
                planned_days=planned_days, reliability_profile=reliability_profile,
                target_status=target_status if target_status != "Cancelled" else "Cancelled",
            ))

            if target_status == "Cancelled":
                writer.add((
                    order_id, f"PROD{order_id:08d}", cust.customer_id, product["product_id"], plant_id,
                    machine_id, supervisor_id, order_date, quantity_ordered, unit_price, total_value,
                    planned_start, planned_end, None, None, 0, 0,
                    "Cancelled", priority, reliability_profile, 0, False,
                ))
                active_orders.pop()  # cancelled orders don't get a production_log simulation
                continue

            # Placeholder row - quantity_produced/quantity_rejected/order_status/delay_days/
            # at_risk_flag/actual_start_date/actual_end_date are finalized after the
            # production_log simulation (UPDATE pass), mirroring how a loan's DPD/NPA
            # flag is only known once its repayment schedule has been simulated.
            writer.add((
                order_id, f"PROD{order_id:08d}", cust.customer_id, product["product_id"], plant_id,
                machine_id, supervisor_id, order_date, quantity_ordered, unit_price, total_value,
                planned_start, planned_end, None, None, 0, 0,
                "In Progress", priority, reliability_profile, 0, False,
            ))

    writer.flush()
    log(f"production_orders: {writer.total} rows")
    return writer, active_orders


def simulate_and_write_production_log(
    orders: list[ProdOrder], employee_ids_by_plant: dict, machine_ids_by_plant: dict, conn,
):
    writer = CopyWriter(conn, "production_log", [
        "log_id", "production_order_id", "log_date", "shift", "planned_qty", "produced_qty",
        "rejected_qty", "machine_id", "operator_employee_id", "downtime_minutes", "log_status",
    ])

    log_id = 0
    results: dict[int, dict] = {}

    for o in orders:
        params = RELIABILITY_PARAMS[o.reliability_profile]
        daily_planned_qty = max(1, round(o.quantity_ordered / o.planned_days))

        if o.target_status == "Completed":
            days_to_simulate = o.planned_days + (random.randint(0, 15) if random.random() < 0.25 else 0)
        else:
            elapsed = (TODAY - o.planned_start_date).days
            days_to_simulate = max(1, min(elapsed, o.planned_days * 3))

        disrupted = False
        produced_total = 0
        rejected_total = 0
        cur_day = o.planned_start_date
        day_statuses: list[str] = []
        employee_pool = employee_ids_by_plant.get(o.plant_id) or []
        machine_pool = machine_ids_by_plant.get(o.plant_id) or ([o.machine_id] if o.machine_id else [])

        for _day_num in range(days_to_simulate):
            if produced_total >= o.quantity_ordered:
                break
            remaining = o.quantity_ordered - produced_total
            planned_qty = min(daily_planned_qty, remaining)

            just_disrupted = False
            if not disrupted and random.random() < params["p_disruption"]:
                disrupted = True
                just_disrupted = True

            if not disrupted:
                produced_qty = round(planned_qty * random.uniform(0.90, 1.05))
                downtime = random.randint(0, 45)
                status = "On Track"
            elif (not just_disrupted) and random.random() < params["p_recovery"]:
                disrupted = False
                produced_qty = round(planned_qty * random.uniform(0.55, 0.90))
                downtime = random.randint(60, 180)
                status = "Delayed"
            else:
                produced_qty = round(planned_qty * random.uniform(0.0, 0.35))
                downtime = random.randint(150, 420)
                status = "Stopped" if produced_qty == 0 else "Delayed"

            produced_qty = min(produced_qty, remaining)
            rejected_qty = round(produced_qty * params["reject_rate"] * random.uniform(0.5, 1.6))
            produced_total += produced_qty
            rejected_total += rejected_qty
            day_statuses.append(status)

            log_id += 1
            writer.add((
                log_id, o.production_order_id, cur_day,
                random.choice(["Morning", "Afternoon", "Night"]),
                planned_qty, produced_qty, rejected_qty,
                random.choice(machine_pool) if machine_pool else None,
                random.choice(employee_pool) if employee_pool else None,
                downtime, status,
            ))
            cur_day = add_working_day(cur_day)

        # A production order's *current* delay is the unbroken run of
        # Delayed/Stopped days trailing at the end of its simulated life so
        # far - a later on-track day is the shop floor catching back up, not
        # ignoring history. Only used for orders still open (not Completed).
        delay_days = 0
        if o.target_status != "Completed":
            trailing_bad_days = 0
            for status in reversed(day_statuses):
                if status in ("Delayed", "Stopped"):
                    trailing_bad_days += 1
                else:
                    break
            delay_days = trailing_bad_days

        quantity_produced = min(produced_total, o.quantity_ordered)
        completed = o.target_status == "Completed" or quantity_produced >= o.quantity_ordered
        if completed:
            final_status = "Completed"
            actual_end = cur_day
        elif o.target_status == "On Hold":
            final_status = "On Hold"
            actual_end = None
        else:
            final_status = "Delayed" if delay_days > 5 else "In Progress"
            actual_end = None

        results[o.production_order_id] = dict(
            quantity_produced=quantity_produced,
            quantity_rejected=rejected_total,
            order_status=final_status,
            delay_days=delay_days,
            at_risk_flag=delay_days > 10 or (final_status == "Delayed" and delay_days > 5),
            actual_start_date=o.planned_start_date,
            actual_end_date=actual_end,
        )

    writer.flush()
    log(f"production_log: {writer.total} rows")
    return results


def backfill_production_orders(results: dict[int, dict], conn) -> None:
    log("Backfilling production_orders from simulated production_log...")
    rows = [
        (r["quantity_produced"], r["quantity_rejected"], r["order_status"], r["delay_days"],
         r["at_risk_flag"], r["actual_start_date"], r["actual_end_date"], pid)
        for pid, r in results.items()
    ]
    with conn.cursor() as cur:
        psycopg2.extras.execute_batch(
            cur,
            """UPDATE production_orders
               SET quantity_produced = %s, quantity_rejected = %s, order_status = %s,
                   delay_days = %s, at_risk_flag = %s, actual_start_date = %s, actual_end_date = %s
               WHERE production_order_id = %s""",
            rows, page_size=5000,
        )
    conn.commit()


def generate_shipments(
    orders: list[ProdOrder], results: dict[int, dict], employee_ids_by_plant: dict, conn,
) -> None:
    writer = CopyWriter(conn, "shipments", [
        "shipment_id", "shipment_number", "production_order_id", "customer_id", "plant_id",
        "shipment_date", "quantity_shipped", "unit_price", "freight_amount", "total_invoice_amount",
        "transporter", "transport_mode", "shipment_status", "delivered_date", "dispatched_by_employee_id",
    ])
    shipment_id = 0
    for o in orders:
        res = results.get(o.production_order_id)
        if not res or res["quantity_produced"] <= 0:
            continue
        n_shipments = 1 if res["quantity_produced"] < o.product["moq"] * 2 else random.randint(1, 3)
        qty_left = res["quantity_produced"]
        base_date = res["actual_start_date"] or o.planned_start_date
        pool = employee_ids_by_plant.get(o.plant_id) or []
        for i in range(n_shipments):
            if qty_left <= 0:
                break
            qty = qty_left if i == n_shipments - 1 else round(qty_left / (n_shipments - i) * random.uniform(0.8, 1.2))
            qty = max(1, min(qty, qty_left))
            qty_left -= qty
            shipment_id += 1
            ship_date = min(base_date + timedelta(days=random.randint(3, 30) * (i + 1)), TODAY)
            freight = round(qty * random.uniform(0.5, 3.0), 2)
            invoice_amount = round(qty * o.unit_price + freight, 2)
            mode = weighted_choice(TRANSPORT_MODES)
            status = weighted_choice([("Delivered", 0.80), ("In Transit", 0.12),
                                       ("Dispatched", 0.06), ("Returned", 0.02)])
            delivered = ship_date + timedelta(days=random.randint(1, 10)) if status == "Delivered" else None
            if delivered and delivered > TODAY:
                delivered = TODAY
            writer.add((
                shipment_id, f"SHP{shipment_id:08d}", o.production_order_id, o.customer.customer_id,
                o.plant_id, ship_date, int(qty), o.unit_price, freight, invoice_amount,
                random.choice(TRANSPORTERS), mode, status, delivered,
                random.choice(pool) if pool else None,
            ))
    writer.flush()
    log(f"shipments: {writer.total} rows")


DOWNTIME_CATEGORIES = [
    ("Scheduled Maintenance", 0.55, "Low"),
    ("Minor Breakdown", 0.28, "Medium"),
    ("Major Breakdown", 0.12, "High"),
    ("Extended Outage", 0.05, "Critical"),
]


def generate_machine_downtime(machines: list[Machine], conn) -> None:
    writer = CopyWriter(conn, "machine_downtime", [
        "downtime_id", "machine_id", "as_of_date", "downtime_category", "downtime_hours",
        "maintenance_cost", "criticality",
    ])
    downtime_id = 0
    for m in machines:
        n_events = np.random.poisson(2.0)
        for _ in range(n_events):
            category, _, criticality = weighted_choice(
                [((c, w, cr), w) for c, w, cr in DOWNTIME_CATEGORIES]
            )
            hours = {
                "Scheduled Maintenance": random.uniform(2, 12),
                "Minor Breakdown": random.uniform(1, 8),
                "Major Breakdown": random.uniform(8, 48),
                "Extended Outage": random.uniform(48, 200),
            }[category]
            cost = round(hours * random.uniform(500, 3500), 2)
            as_of = random_date(date(2023, 1, 1), TODAY)
            downtime_id += 1
            writer.add((downtime_id, m.machine_id, as_of, category, round(hours, 2), cost, criticality))
    writer.flush()
    log(f"machine_downtime: {writer.total} rows")


INSPECTION_STAGES = ["Incoming Material", "In-Process", "Final Inspection", "Customer Return"]


def generate_quality_inspection_records(orders: list[ProdOrder], employee_ids_by_plant: dict, conn) -> None:
    writer = CopyWriter(conn, "quality_inspection_records", [
        "inspection_id", "production_order_id", "product_id", "inspection_date",
        "inspector_employee_id", "inspection_stage", "sample_size", "defects_found",
        "defect_rate_pct", "result",
    ])
    inspection_id = 0
    base_defect_rate = {"Good": 0.01, "Average": 0.03, "Poor": 0.08}
    for o in orders:
        pool = employee_ids_by_plant.get(o.plant_id) or []
        n_inspections = random.randint(1, 3)
        stages = random.sample(INSPECTION_STAGES[:3], k=min(n_inspections, 3))
        for stage in stages:
            sample_size = random.randint(10, 200)
            rate = max(0.0, np.random.normal(base_defect_rate[o.reliability_profile], 0.02))
            defects = min(sample_size, round(sample_size * rate))
            defect_rate_pct = round(100 * defects / sample_size, 2)
            result = "Pass" if defect_rate_pct < 2.0 else ("Rework" if defect_rate_pct < 6.0 else "Fail")
            inspection_id += 1
            inspection_date = min(o.planned_start_date + timedelta(days=random.randint(1, o.planned_days + 5)), TODAY)
            writer.add((
                inspection_id, o.production_order_id, o.product["product_id"], inspection_date,
                random.choice(pool) if pool else None, stage, sample_size, int(defects),
                defect_rate_pct, result,
            ))
    writer.flush()
    log(f"quality_inspection_records: {writer.total} rows")


def generate_payables(received_pos: list[dict], plants: list[Plant], conn) -> None:
    writer = CopyWriter(conn, "payables", [
        "payable_id", "payable_type", "payee_name", "plant_id", "supplier_id", "related_po_id",
        "invoice_number", "amount", "due_date", "paid_date", "status",
    ])
    payable_id = 0
    for po in received_pos:
        payable_id += 1
        due = po["received_date"] + timedelta(days=30)
        paid = due + timedelta(days=random.randint(-5, 20))
        writer.add((
            payable_id, "Supplier Payment", "Raw Material Supplier Payout", po["plant_id"],
            po["supplier_id"], po["po_id"], f"INV{payable_id:08d}", po["total_amount"], due,
            paid if paid <= TODAY else None, "Paid" if paid <= TODAY else "Pending",
        ))

    vendor_types = ["Utility Bill", "Contractor Payment", "Equipment Lease", "Freight Charges", "IT/Software AMC"]
    for _ in range(max(300, len(plants) * 20)):
        payable_id += 1
        p = random.choice(plants)
        due = random_date(date(2023, 1, 1), TODAY + timedelta(days=30))
        paid = due + timedelta(days=random.randint(-5, 25))
        writer.add((
            payable_id, random.choice(vendor_types), fake.company(), p.plant_id, None, None,
            f"INV{payable_id:08d}", round(random.uniform(5_000, 800_000), 2), due,
            paid if paid <= TODAY else None, "Paid" if paid <= TODAY else "Pending",
        ))
    writer.flush()
    log(f"payables: {writer.total} rows")


def generate_ledger(orders: list[ProdOrder], received_pos: list[dict], conn) -> None:
    writer = CopyWriter(conn, "transactions_ledger", [
        "transaction_id", "reference_number", "production_order_id", "customer_id",
        "transaction_type", "transaction_date", "amount", "payment_mode", "status",
    ])
    txn_id = 0
    for po in received_pos:
        txn_id += 1
        writer.add((
            txn_id, f"TXN{txn_id:010d}", None, None, "Raw Material Purchase",
            po["received_date"], po["total_amount"], "NEFT", "Success",
        ))
    for o in orders:
        txn_id += 1
        invoice_amount = round(o.quantity_ordered * o.unit_price, 2)
        writer.add((
            txn_id, f"TXN{txn_id:010d}", o.production_order_id, o.customer.customer_id,
            "Sales Invoice", o.order_date, invoice_amount, "Letter of Credit", "Success",
        ))
        if random.random() < 0.75:
            txn_id += 1
            payment_date = o.order_date + timedelta(days=random.randint(20, 90))
            writer.add((
                txn_id, f"TXN{txn_id:010d}", o.production_order_id, o.customer.customer_id,
                "Payment Received", min(payment_date, TODAY), invoice_amount,
                random.choice(PAYMENT_MODES), "Success",
            ))
    writer.flush()
    log(f"transactions_ledger: {writer.total} rows")


# --------------------------------------------------------------------------
# Main
# --------------------------------------------------------------------------

def main():
    parser = argparse.ArgumentParser(description="Generate the synthetic manufacturing-company demo database.")
    parser.add_argument("--scale", choices=list(SCALE_PRESETS.keys()), default="full")
    parser.add_argument("--db-url", default=os.getenv("MANUFACTURING_DATABASE_URL", "postgresql://saarthi:password@localhost:5432/postgres"))
    parser.add_argument("--db-name", default="manufacturing_demo_db")
    args = parser.parse_args()

    preset = SCALE_PRESETS[args.scale]
    log(f"Scale='{args.scale}' preset={preset}")

    ensure_database(args.db_url, args.db_name)
    target_url = derive_db_url(args.db_url, args.db_name)
    conn = psycopg2.connect(target_url)
    conn.autocommit = False

    t0 = time.time()
    with conn.cursor() as cur:
        log("Creating schema...")
        cur.execute(SCHEMA_SQL)
    conn.commit()

    plants = generate_plants(preset["plants"], conn)
    employee_ids_by_plant = generate_employees(preset["employees_per_plant"], plants, conn)
    suppliers = generate_suppliers(preset["suppliers"], plants, conn)
    machines, machine_ids_by_plant = generate_machines(preset["machines_per_plant"], plants, conn)
    products = generate_products(conn)
    materials = generate_raw_materials(conn)
    generate_bom(products, materials, conn)
    customers = generate_customers(preset["customers"], plants, conn)

    received_pos = generate_purchase_orders(suppliers, materials, employee_ids_by_plant, conn)

    _, active_orders = generate_production_orders(
        customers, products, plants, machine_ids_by_plant, employee_ids_by_plant,
        preset["orders_per_customer"], conn,
    )
    results = simulate_and_write_production_log(active_orders, employee_ids_by_plant, machine_ids_by_plant, conn)
    backfill_production_orders(results, conn)

    generate_shipments(active_orders, results, employee_ids_by_plant, conn)
    generate_machine_downtime(machines, conn)
    generate_quality_inspection_records(active_orders, employee_ids_by_plant, conn)
    generate_payables(received_pos, plants, conn)
    generate_ledger(active_orders, received_pos, conn)

    log("Creating indexes...")
    with conn.cursor() as cur:
        cur.execute(INDEX_SQL)
    conn.commit()

    with conn.cursor() as cur:
        cur.execute("SELECT pg_size_pretty(pg_database_size(%s))", (args.db_name,))
        size = cur.fetchone()[0]

    elapsed = time.time() - t0
    log(f"Done in {elapsed:.1f}s. Database '{args.db_name}' size: {size}")
    conn.close()


if __name__ == "__main__":
    main()
